### ISSUE TITLE
What is the expected behavior of DX12 errors?

### ISSUE THREAD

**Issue by weltkante** [Microsoft/DirectX-Graphics-Samples#100]
While trying out if the debug layers work (for answering issue #99 ) I created a DepthStencilView with an invalid Format because I figured that's something the debug layers can pick up and report easily.

The debug layer did pick this up, but as a side effect Windows and/or the graphics driver totally freaks out, _the full screen just shows black/white bars for a few seconds_, Windows keeps restarting the driver until it gives up and switches the application to the warp driver. (Nice fallback btw!)

So I figured it's worth asking what the expected behaviour of DX12 API errors is. Are they expected to freak out the whole screen if I'm not in fullscreen mode? From my previous experience I'd have expected the driver to be restarted and/or the application to crash, possibly the window to show garbage, but not the full screen. Since the debug layer does pick up the error I kinda suspect there's a driver bug involved, but maybe I'm all wrong and the screen freaking out is an expected response to a DX12 error? It's a low level API after all.

If you want to reproduce this, I'm on a Surface 4 and changed the format of the D3D12_DEPTH_STENCIL_VIEW_DESC to DXGI_FORMAT_R32_FLOAT in the "DirectX 12 App (Universal Windows)" template. I also opened [an issue](https://software.intel.com/en-us/forums/graphics-driver-bug-reporting/topic/610096) for this on the intel forums in case it is a driver bug and they want to investigate

**Comment by bobbrow** [comment]
I meant to post a note yesterday that I borrowed a Surface Pro 4 and was able to reproduce your issue but wasn't able to dig in deep because I got pulled into something else.

What I would normally expect from a device removed event is that either the window would appear to hang for a few seconds, or in the worst case the screen might flash black.  The WARP fallback is intended when an app is behaving badly.  In this case, since the VS template attempts to recover from device removed errors, it was essentially spamming the driver with bad calls, so Windows disabled access to it.  When I reproduced your scenario, I also saw a toast notification to this effect.

One thing I noticed though was that if I disabled the SDK Layers, I saw the expected device removed behavior (no black&white bars).  I think there's a bug here, but I'm not certain that the Intel driver is to blame.  I'm going to have to come back to this later in the week.

**Comment by weltkante** [comment]
> What I would normally expect from a device removed event is that either the window would appear to hang for a few seconds, or in the worst case the screen might flash black.

That's what I wanted to know, thanks.

FYI (in case it was not coordinated) someone on the intel forum thread linked above said they discovered and fixed a driver issue related to the problem.

As far as I'm concerned my question is answered, if you don't need the issue to track the problem you can close it. Thanks again for looking into it.

**Comment by bobbrow** [comment]
Excellent!  Glad to hear that Intel was able to root cause this.
