### ISSUE TITLE
PixelBuffer::CreateTextureResource with CreatePlacedResource not yet supported?

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#113]
Hi Guys,

Just curious, it seems the VidMemPtr param in PixelBuffer::CreateTextureResource is not used in current version. So I assume in the near future miniEngine will support CreatePlacedResource where we could potentially have multiple texture share the same GPU memory? Or the CreatePlacedResource method is not recommended?

Thanks

Peng

**Comment by stanard** [comment]
That's a good question.  MiniEngine also supports Xbox One though not in the GitHub version due to NDA and licensing issues.  That bit of code is active in the Xbox One code path.  (It's very common to alias surfaces in ESRAM because it's fast but small.)  We intend to improve memory management overall and support such things as buffer lifetimes and memory aliasing.  Placement create is also very effective for reducing waste from single allocations not completely filling memory pages.  Beyond that, we also want a robust streaming system, use virtual memory for partially resident surfaces, and handle reduced memory scenarios like when you suddenly don't have enough video memory and need to decide what to evict back to system RAM.

We appreciate your questions and suggestions.  That's why we're here!  :-)

Cheers,
James

**Comment by pengliu916** [comment]
Thanks James, it will be really nice to see miniEngine elaborate PlaceResource usage in the near future (maybe enable dynamic resolution on scene rendertarget where all rendertargets have same gpu address?)

Anyway, thanks again for your time, it's really nice to have you guys aside helping us learn dx12
