### ISSUE TITLE
The concept behind DynamicDescriptorHeap

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#114]
Hi Guys,

I have a hard time to fully grasp the idea behind DynamicDescriptorHeap class and its proper usage. To me, it looks like the normal DescriptorHeap could almost do everything, so what the advantages of using DynamicDescriptorHeap? and in which scenario we do have to use DynamicDescriptorHeap?

An usage case example will be greatly appreciated

Thanks

Peng

**Comment by stanard** [comment]
Descriptor heaps are one of the big changes with DX12.  The idea with them is that you can create an array of descriptors (which are compact, GPU-specific encodings describing each resource) and bind several descriptors with one API call.  The root signature describes how the descriptor table lines up with input resources.  This paradigm favors load-time computation rather than run-time computation, so the CPU does less work each frame.  But the downside is that it's not easy to dynamically build up descriptor tables on the fly.  Maybe you just want to change one texture, or maybe you don't know what resource you'll be using at startup because it changes every frame.  To be easier to use and for quick experimentation, we created a dynamic descriptor heap.  This is much like a dynamic constant buffer.  So rather than creating an immutable buffer at startup, you might prefer to lazily set values.  The dynamic descriptor heap is so useful, that we don't even bother with static descriptor heaps in MiniEngine (yet).

To understand even better, I can walk you through what has to happen in a dynamic descriptor heap.  But first, let's recall how it works in DX11 (and below).  In DX11, you have shader stages and bind slots.  You can bind a resource to exactly pixel shader texture slot 3 and nowhere else if you want.  Then if you change pixel shader texture slot 2, you would expect slot 3 still has the same texture bound.  If you set vertex shader texture slot 3, it does not change what texture is bound to pixel shader slot 3.  This is the kind of behavior we're going for with dynamic descriptor heaps.

Now descriptors are opaque graphics state.  That means we can get a pointer to one, but we shouldn't manipulate them directly.  Instead what you can do is create a CPU-visible heap where you first construct a descriptor, then you copy descriptors to a GPU-visible heap.  If you bind a descriptor table--which is a list of descriptors--to your shader pipeline, the descriptors have to be in the right order and at the right offsets.  So we copy them into place in the GPU-visible heap, set the heap pointer, and set the offset to the first descriptor.  The GPU won't actually see this descriptor table for some time, and it's hard to know when it's finished reading it without closing your command list and inserting a fence.  (We don't do those very often.)  So if you want to make a change to your descriptor table for the next draw call, you have to make a whole new copy with your modifications.  This is why the dynamic descriptor heap needs to have a CPU-visible cache of descriptors.  Every time we issue a draw, we see if any of the cached descriptors have changed and upload a new copy of the table (and set a new offset).  If we run out of room in the descriptor heap, we need to allocate a new one, re-upload our existing descriptor tables, and schedule the old heap for lazy cleanup.

It's also important to know that if you are creating command lists on multiple threads, each command list must have its own dynamic descriptor heap.  This makes allocations lock-free and all of the dynamic descriptor heaps can be cleaned up when this command list's fence completes.

As a final note, this is very similar to how DX11 implements resource binding, and we know it's non-optimal (though I've tried to make the system as fast as possible.)  For best DX12 performance, you want to pre-build descriptor tables/heaps.

I hope that helps!

Cheers,
James

**Comment by pengliu916** [comment]
Thanks James, I need sometime to digest all these, and probably will have to bother you guys later on that :-)

**Comment by manaskulkarni** [comment]
Hi James,
What do you mean exactly by pre-building a descriptor heap?
How can we make sure that the descriptors in the table are contiguous if the heap is pre-built?
Lets say there are two descriptor tables:
Table 1: Cbv A, Texture A, Texture C
Table 2: Cbv B, Texture A, Texture D
Now when we call SetGraphicsRootDescriptorTable, how can we make the descriptor handles contiguous with a pre-built heap?
I am still trying to figure out how to avoid the CopyDescriptor operation. I can get it to be just 1 dynamic heap and each command list is assigned a part of the heap but cannot make everything pre-built.
Any guidance will be really appreciated.
