### ISSUE TITLE
Guidance on using split resource barrier

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#117]
Hey guys,

From what I know so far the split resource barrier introduces a way in which you could overlay some of you GPU task with resource transaction instead of stalling on it. But there are basically two kinds of question bothers me:

1. Which type of resource transaction is worthy using split resource barrier? ( I assume using split resource barrier will have a higher cost than its alternative? I know when you transform a depth view to srv, it involve some kind of decoding, which make it more expensive than other simple transaction.... So it will be great if you guys could list bunch of transaction type which worthy using split barrier)

2. Which type of GPU task will be the best to overlap with resource transaction? ( My guess is that some resource transaction will put some pressure on memory bandwidth, so should we put some ALU intensive tasks to overlap with it? But I may be really wrong....)

Thanks in advance for all your help

Peng

**Comment by stanard** [comment]
These are very good questions.  Basically, all resource barriers will incur a pipeline flush.  This involves waiting for pixel and compute shaders to complete followed by cache flushes and invalidation.  Some resources like RTVs and DSVs may have to flush associated metadata as well and then need to be decompressed.  Any time you clear an RTV or DSV, you put it back into a compressed state.  After writing to those targets, if you then transition to an SRV, they will need to be decompressed.  Once decompressed, they will stay decompressed until you clear them again.

It's true that decompression is much more expensive than a standard resource barrier, but all resource barriers can cause bubbles of inactivity on the GPU.  So you should make an effort to split any resource barrier you possibly can to give the driver an opportunity to smooth out the bubble.  But you should especially try to split barriers when transitioning from RTV or DSV to SRV.

And to go into a little more detail about what splitting a barrier does, let's think about how producers and consumers work.  If you are rendering a texture or writing data to a buffer, you are "producing".  If a subsequent process needs to read in that texture or data, it is "consuming".  The consumer needs to make sure that all writes have completed and that they are committed to memory before it begins.  If the consumer immediately follows the producer, all of the producer's waves need to finish, and some of those waves might finish much later than others, so GPU threads are starting to idle.  Once the GPU is completely idle, the cache lines must be evicted and invalidated so that all data makes its way to memory.  Finally, the consumer can begin.  Now if you don't need to start consuming immediately, you can instead issue other work that can fill in all those idling threads.  By the time the consumer wants to start, it just has to ask, "are we sure the producer's threads are done"?  If so, do a cache flush (which can happen while threads are still reading and writing through cache), and begin consuming.  So, as you noted, the primary benefit of splitting barriers is that you can slot work in between to keep the GPU busy.  You still need cache flushes though.

Now to answer the question about what tasks overlap best, in the case where you don't have to decompress anything, then anything will do.  The GPU is just starting to idle cores, so get it working again on something else.  In the case where you are decompressing a buffer (RTV or DSV), those are bandwidth-intensive operations but don't use ALU (shader cores).  So you might get slower memory speeds, but you can still run anything to avoid idling.

I hope that helps!

-James

**Comment by pengliu916** [comment]
That's really instructive. Thanks so much for elaborating on that. I will close this issue to make your issue dashboard clean and tidy~

**Comment by SungJJinKang** [comment]
@stanard 
How does driver decide what overlaps with memory barrier.
Do they have some rules?
