### ISSUE TITLE
DescriptorHeap Management (on host side)

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#120]
Hi Guys,

I am thinking of using miniEngine to create a highly dynamic 3D application where I have maybe hundred  and thousands of object created and destroyed on the fly. For resource management, it looks ok for miniEngine since the use of dynamic descriptor heap. But in my case, each object will have its own rendertarget (for interesting simulation), and should be created and destroyed depend on object's lifetime. The problem here is the RTV is managed by DescriptorHeap which doesn't seem to have a way to release dead RTV descriptor resource. Though the memory for store each RTV descriptor is negligible, but as my  dynamic app runs, it will keep consuming unnecessary memory which essentially act like memory leak...

So I just wondering maybe miniEngine does have proper way to manage RTV resource but I just missed it or it is a potential issue with miniEngine?

Thanks

Peng

**Comment by stanard** [comment]
The descriptor management system in MiniEngine isn't designed for long-lived and highly dynamic games.  It's assumed you will create a fixed number of resources at startup, and you won't want to reclaim any descriptors.  Well, actually it does reclaim descriptors when the engine goes through a resolution change.  This idles the GPU so that no resources are needed anymore, then it recreates descriptors for all the same resources in all the same places but with new dimensions.  This will probably stall the GPU for 30 ms or so, which is not something you want to do hundreds of times per frame.

If you are both increasing and decreasing the number of resources over time, and you want to reuse descriptors, then you'll need to keep track of which descriptors are deprecated and whether they are still needed by the GPU.  We're talking about a basic allocator system that supports deferred deletion and a quick search for unused allocations.  Fortunately, all descriptors in a heap are a fixed size, so you could probably use a bit mask to indicate which descriptor indices are available and use a _BitScanForward() or _BitScanReverse() type function to quickly search for set bits.  I hope that idea helps, and maybe in the future we'll try to develop this too.  It wouldn't hurt to make MiniEngine more robust to support more use cases!

Cheers,
James
