### ISSUE TITLE
Add steps for setting up D3D12 Debug Layer Output

### ISSUE THREAD

**Issue by dustin-biser** [Microsoft/DirectX-Graphics-Samples#128]
I assume one of the goals of these samples is to help people get up and going very quickly with D3D12.  Having installed a new copy of Visual Studio 2015 Community Edition, I was surprised at how many steps it took (and how many hours of searching online) to get the Debug Layer messages to display correctly in Visual Studio's Output Debug Window.  By default, nothing shows up and there are a bunch of steps to get debug output messages displaying correctly.   I took the time to describe all the necessary steps in a somewhat painstaking fashion here:
http://dustin-biser.me/blog/2016/4/2/d3d12-debug-layers-and-output

Perhaps we could add this link, or at least copy some of these steps to the main ReadMe.md so people new to D3D12 or VS2015CE can benefit and get up and going as fast as possible.

**Comment by bobbrow** [comment]
Thank you for the feedback.  I looked over your blog post.  The reason no debug messages show up by default with these samples is because we try not to ship any code that has warnings or errors in it. :)  ... and "Info" is way to noisy to leave on by default (as you have noted).  But all of the other settings you mentioned in your post should already be configured by default when you install Visual Studio 2015.  Was this not the case for you?

Using the DirectX Control Panel (dxcpl.exe) is completely optional.  Your blog post seems to be asserting that you must set the path to your project in order for the debug layers to work, but this is not the case.  Regardless, I agree that there would be some benefit to describing the DirectX Control Panel (dxcpl.exe) somewhere and will look into it.  Current search results are pretty weak in this area.  Something that you may not have been aware of is that the same settings you see in the control panel are also available in code.  You can check out the MiniEngine project for some [example code](https://github.com/Microsoft/DirectX-Graphics-Samples/blob/master/MiniEngine/Core/GraphicsCore.cpp#L314) on how to set up filters for the debug layer.

**Comment by dustin-biser** [comment]
All of the settings in my post I had to manually set, except checking "Program Output" from the Debug Output Window, which was the only item enabled by default.

Interestingly, when I remove my top-level project folder from the Scope of the DirectX Control Panel Properties, I no longer see D3D12 Info messages (even though they are un-muted and should display).  Only when adding my top-level project folder to the Scope list do the D3D12 Info messages to display correctly.  Perhaps I am missing an Windows/VS update patch? I'm using VS 2015 version 14.0

Thanks for the example code link.

**Comment by bobbrow** [comment]
The default behavior of d3d12sdklayers is to filter out INFO messages.  That's why you don't see any unless you enable them in dxcpl or in code.  CRITICAL, ERROR, and WARNING messages will appear without changing any of the default settings, but we try not to ship code that has any of those. :)
