### ISSUE TITLE
IndexBuffer Exceeds Virtual Address Range

### ISSUE THREAD

**Issue by dustin-biser** [Microsoft/DirectX-Graphics-Samples#129]
Running the D3D12Multithreading sample causes the following D3D12 Error to be reported each frame:

`D3D12 ERROR: ID3D12CommandList::IASetIndexBuffer: pDesc->BufferLocation + SizeInBytes - 1 (0x000000020510a4cb) exceeds end of the virtual address range of Resource (0x0000000000000000, Debug Name: '(nullptr)', GPU VA Range: 0x0000000204e1d000 - 0x0000000204e2cfff). This is OK as out of bounds access is guarded by the GPU (writes are discarded and reads return 0). However the developer probably did not intend to make use of this behavior.  [ STATE_CREATION ERROR #725: SET_INDEX_BUFFER_INVALID]`

**Comment by bobbrow** [comment]
This is issue #76.  It's a bug in d3d12sdklayers.dll which was fixed in February.  I'm not sure if you've got all of the latest patches for Windows 10 installed (KB3140743 is the one you're looking for), but if you have all of those installed and are still seeing this, then we would like to know.  Optional features that are installed after the patch has been released for them are supposed to be updated shortly after they are installed (within a day, I believe).

**Comment by bobbrow** [comment]
Sorry, I misspoke.  The patch went out March 1st, not in February.

**Comment by dustin-biser** [comment]
I see I am on build 10240, so I have not gotten any of the latest updates.  So that's my fault.  Feel free to close this item. Thanks!

**Comment by bobbrow** [comment]
Thought I would add a note... When you upgrade to 10586, your Graphics Tools optional feature will be uninstalled.  Please reinstall it through the Settings app (search for "optional features") before installing the patch.
