### ISSUE TITLE
DX12+XAML for UWP template

### ISSUE THREAD

**Issue by thecobblersfather** [Microsoft/DirectX-Graphics-Samples#135]
I brought this up the other day in a closed thread, so I am creating a new one. Feel free to tell me to close this one if needed.

Has there been any update on the DX12+XAML for UWP template? I am currently developing a C#/C++ Direct2D application and have run into an issue creating my SwapChainPanel.

**Comment by bobbrow** [comment]
Can you help me understand why you're choosing to use DX12 for a Direct2D application?  Direct2D is using D3D11 under the hood, so if you're using only Direct2D, I recommend you stick with the D3D11+XAML for UWP template for now.

The DX12+XAML template is close to being ready for GitHub, but higher priority stuff keeps preempting my work on it.  I suppose I could release it in its current state in a branch off of develop until I feel it's ready for prime time.

**Comment by thecobblersfather** [comment]
I chose DX12 simply because I assumed being 12 vs 11 was the most up to date version of DX.

**Comment by walbourn** [comment]
Direct3D 12 is intended for graphics experts looking to have maximal control over the CPU usage, memory, and GPU/CPU synchronization. As such, it is significantly more challenging to use than DirectX 11. Direct3D 11.3 on Windows 10 can use all the same hardware features as Direct3D 12 including ``D3D_FEATURE_LEVEL_12_0`` and ``D3D_FEATURE_LEVEL_12_1``. Also keep in mind that there are no drivers that support DX12 at this time for Feature Level 10.1, 10.0, or 9.x hardware so addressing those devices requires DX11.

**Comment by jxl98c** [comment]
Whilst I appreciate you may have answered the original post there are plenty of other people in the community who would like to see this sooner rather than later.  A lot of us have been stung in the past by having to migrate through numerous major revisions of Direct3D.

I for one would like to keep my code base on the latest revision so that when I want to use some whizz-bang feature in the future I do not have to jump from D3D11 to D3D13 and have a migration horrorshow on my hands because we all followed the advice and stuck with what was 'just good enough'.

I think it is perfectly reasonable to expect someone with only a Direct2D requirement to want to have their codebase on the latest version - if only for maintenance sake.

**Comment by weltkante** [comment]
@jxl98c you seem to not understand what DX12 is, and its relation to DX11.

There is no point migrating to D3D12 if you are "just using Direct2D" because Direct2D is based on D3D11; so you why port to D3D12 if you just have to put a D3D11 interop device on top of it to use D2D?

D3D11 and D3D12 are living alongside and have different target audiences. Maybe it was a mistake to name it D3D12 and they should have made a new name.

**Comment by jxl98c** [comment]
@weltkante - I understand perfectly what D3D12 is and its relation to D3D11 and probably should have clarified in my post.

I am not using Direct2D, My reference to it was actually only in relation to the comments in the original post.  I am currently working on procedural terrain generation and a Spherical ROAM algorithm which is computationally heavy and written entirely using Direct3D (not 2D) and I would like this to be based on the current version of Direct3D+XAML in a UWP app for a number of reasons.

I may consider offloading some of the work on to the GPU at some point and D3D12 may make that easier (or perhaps I wont).  Either way, it doesn't really matter does it?  The answer should either be "we have no intention to provide this" or "we are working on it", and not to start trying to get into the heads of developers trying to be creative and second guess their motives.

I also work with a lot of clever Mathematics boffins who also happen to be C# developers (I work for a leading finance company) and given that most of my optimisation work is centred around complex mathematical simplification and I'd like to share some of my problems - a XAML app would let me port it to C# too (SharpDX perhaps) and give others an opportunity to share my workload.

Whilst I'm sure there are other options, and alternative implementations, I should point out that Microsoft are dying (have just died?) in the mobile market and everyone is whining about the lack of decent applications / games.  When people in the community ask for a D3D12+XAML for UWP sample I guess I'd expect them to jump at the chance to offer it.

Ultimately, I guess it's just something I expect to be provided for the platform.

**Comment by walbourn** [comment]
A Direct3D 12 + XAML with C++ code-behind is probably doable today, but C# requires some Direct3D 12 assemblies. I believe [SharpDX](http://sharpdx.org/) has Direct3D 12 support.

**Comment by bobbrow** [comment]
I don't think we've been dodging the answer to this question.  I opened Issue #20 for this long ago and also mentioned in this thread that I have a working version of it but haven't made it available yet.

I apologize if this isn't meeting anyone's timelines for mobile right now, but please be aware that there aren't any Windows Phones on the market today that support D3D12.

If enough people want this I can bump up the priority on it, but the real motivating factor here is that we have received very little feedback about the lack of the D3D12+XAML template and have been focusing on other things as a result of that.

**Comment by jxl98c** [comment]
Thanks for the speedy response @walbourn.  SharpDX does indeed have Direct3D12 support but they are awaiting a Direct3D12+XAML UWP sample in C++ before they port it to SharpDX.  They currently only have samples for what is on here on.  I've tried a number of different attempts to get this working myself but keep failling when it comes to wiring up a SwapChain to a SwapChainPanel (or something like that - I've not got the code to hand).

**Comment by jxl98c** [comment]
@bobbrow - yes, sorry, you did mention you had been working on it - I got myself worked up and forgot you'd mentioned that :-)

There are a few people asking for it on various forums - perhaps not on here.  There seems to be a renewed interest in it now that the XBone has the new developer mode - it's certainly why I have renewed interest.

I'm aware the phones don't support it yet (maybe they never will) but I do have a 950XL and I know that Qualcomm and MS did do a collaboration to ensure that the GPU is DX12 compatible, even if it's not currently feature ready in the OS.

**Comment by bobbrow** [comment]
That's fair feedback.  Let me recompile what I have, write some notes, and get it up on a branch off of develop.

**Comment by jxl98c** [comment]
That would be really useful @bobbrow and I appreciate the effort.  The universal app is pretty magic and I'm surprised it doesn't get more interest from the likes of Android / iOS developers when they could target XB, Windows Phone and Windows in one go.  If people can get good DX12 support on it from their favourite language and XAML too then it would be pretty sweet.

**Comment by bobbrow** [comment]
I just published a new branch with the template in it.  I haven't gone back to see if all of the recent changes I've made to the DX12-only template have been applied to this version since I've literally been sitting on this code for months, but this should serve as a starting point for anyone who is interested in XAML.

https://github.com/Microsoft/DirectX-Graphics-Samples/tree/feature_xaml_template/Templates/DirectX12XamlApp

**Comment by bobbrow** [comment]
If there are any more XAML-related questions, please feel free to open a new issue.  I believe the original issue has now been addressed.
