### ISSUE TITLE
Better container for lazy clean up?

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#142]
Hey Guys,

From what I can see, miniEngine uses queue for lazy clean up (fence value and resource pair get inqueue when jobs submitted to GPU, and dequeue after it's fence value get reached and been requested). It seems by using queue as container, miniEngine assume GPU process job in a 'first come first finish' fashion. But does that assumption hold? even within the same command queue? will there be any case where a small independent job submitted later will be finished earlier than the older big job? If that is the case, will it be better to use minimum heap for lazy clean up container? though there will be a small CPU overhead...

Please correct me if I missed something there.
Thanks

Peng

**Comment by pengliu916** [comment]
I know where I got something wrong... fence may be reached out of order, but we can't check which fence get reached first based on fence value... so even if the 'first come first finish' assumption doesn't hold, it's not something can be solved by using minimum heap...

**Comment by stanard** [comment]
In a single-threaded renderer, this assumption that resources will retire in order is valid.  But this pattern of using a queue for lazy cleanup and checking only the item at the front of the queue will work in a multi-threaded renderer too.  These systems are designed to recycle resources if possible, but if not, then to allocate another.  Because we don't walk the queue looking for candidates, we might miss opportunities to recycle, so we end up using more memory.  But those resources will eventually get recycled.  And if the queue gets long enough (through over-allocating resources), it's almost guaranteed that the first resource in the queue will be ready and waiting for a (relatively) long time.  However, I have thought about taking a pruning pass to free up excess bloat.  Perhaps every frame you can walk the entire queue and release (not recycle) resources that have passed their fence.

**Comment by pengliu916** [comment]
Thanks James for elaborating on that. But I am a little bit confused that you said 'resource will retire in order'. Does that mean GPU tasks submitted to GPU will be flatted in one command queue without overlap? Otherwise if two jobs can be overlapped, the retire order should then depend on how much time the GPU spend on each task.

Please correct me if I have some fundamental misunderstanding of the workflow in command queue.
Thanks
