### ISSUE TITLE
Buffer out of bound access behaviour

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#144]
Hey Guys,

I have noticed that the d3d11 normal 'guaranteed return 0 when access buffer out of bound in shader' is not hold in dx12 (it will crash in my case).

So for example you have a bufferSRV in shader, if you use index to access it and when the index>bufferWidth*bufferHeight you will get GPU hang in DX12, but in dx11 or older, access out of bound will just return 0.

It will be greatly appreciated if somebody could verify that this is the on-purpose behavior for out of bound access in dx12, and provide some tips or work around to bring back the 'guaranteed return 0' for dx12 (doing boundary check in shader may not be a good idea in terms of performance, I guess....)

Thanks in advance

Peng

**Comment by bobbrow** [comment]
Are you using a root descriptor or a descriptor table in your root signature?  D3D12 introduces a complication with regard to root signatures.  If the buffer is described by a normal descriptor in a descriptor table, you should get D3D11 behavior (return 0), but if you use a root descriptor, you get undefined behavior on out of bounds, since the root descriptor does not capture bounds information.

Jesse goes into some additional detail in [this gamedev.net post](http://www.gamedev.net/topic/677978-hlsl-reading-outside-array-safe/)

**Comment by pengliu916** [comment]
Thanks Bob,

So if I understand it correctly, the reason why GPU will crash on root descriptor is because root descriptor is just the raw pointer to that buffer without proper size information. So GPU have no way to do boundary check, while in descriptor table, the GPU then have full information about that buffer so out of bound access can be detected and handled by returning 0.

What interests me is that, for root srv, write out of bound causes crash makes sense since it may corrupt other data. But why reading out of bound could also crash GPU? Is there some driver level memory guard to protect data, which will remove device once access violation is detected?

Thanks

Peng
