### ISSUE TITLE
DX12 support bounding resource both as SRV and UAV at the same time?

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#145]
Hi there,

IIRC, in dx11 we can't bound one buffer both as SRV and UAV at the same time, which makes sense to me...

But after looking through MiniEngine FXAA implementation, it seems the g_SceneColorBuffer is bound as [SRV ](https://github.com/Microsoft/DirectX-Graphics-Samples/blob/master/MiniEngine/Core/FXAA.cpp#L175)and [UAV ](https://github.com/Microsoft/DirectX-Graphics-Samples/blob/master/MiniEngine/Core/FXAA.cpp#L170)for the final pass (though that resource is in D3D12_RESOURCE_STATE_UNORDERED_ACCESS state).

So my questions are:
1. in DX12, can we bound resource both as SRV and UAV simultaneously? And if yes, what's the purpose of supporting it?
2. Why the validation layer won't complain that your resource is not in xxx_shader_resource state while you are using it as SRV?
2. Why in MiniEngine FXAA implementation we need both SRV and UAV for scenebuffer, since we can read from UAV?

Thanks in advance for anyone kindly taking the time answering my questions

Peng

**Comment by stanard** [comment]
Hi Peng,

You've touched on a "dirty little hack" in MiniEngine.  It's already been modified locally, and should be pushed to GitHub soon.

So the situation is that there are times when you want to read-modify-write a UAV.  Some image algorithms work better this way.  It can avoid a buffer copy, and it can keep image pipelines simple by not moving your data around.  For a GPU to do this with typed UAVs, it has to be capable of "typed UAV loads".  (Typed UAVs are any other than UINT formats.)  The shader would do a typed load, work with the data, and then do a typed store.  So it turns out that this capability is not that widespread yet.  NVidia's Kepler architecture, for instance, does not support typed UAV loads.  As an experiment, I discovered I could fake typed UAV loads by replacing them with typed _SRV_ loads.  I felt that either the capabilities reported by the GPU must be conservative, or perhaps not all UAV types were supported, but certainly the one I cared about was:  R11G11B10_FLOAT.  By binding a resource as both an SRV and a UAV, I could get typed loads even on Kepler.  The main issue with it is that it's not officially sanctioned to bind a resource in two states, and the validation layer gets very confused.

Discussing the reasonable goal of read-modify-write algorithms with the DirectX team, we determined that the most appropriate solution to support GPUs lacking typed UAV loads is to instead do an _untyped_ UAV load, manually decode the format from UINT, then modify and write.  While an easy change, it turns out there is another gotcha.  You can't create an R32_UINT view of an R11G11B10_FLOAT buffer.  This restriction was somewhat arbitrary and will be relaxed in a future DX12 release.  In the mean time, I will use a trick where two views look at different resources occupying the same memory.  Using an ID3D12Heap and CreatePlacedResource(), I can overlay (or alias) my two UAVs.

So now I'll answer your questions.

1) Yes, you can, but no you should not.  The purpose was explained above.
2) I disabled the validation layer and will be re-enabling it in the next push.  It may be possible to ignore certain validation warnings.
3) I think the reason for using this hack with FXAA should be explained by now, but it modifies an R11G11B10_FLOAT buffer in place.  The luminance buffer is a separate SRV, so it won't be modified.  But since FXAA does need to blend a pixel with its neighbor, neighbor pixel colors need to be copied to somewhere else.  These colors are copied to the work queues (append buffers).

I want to follow up with a word of caution.  Read-modify-write algorithms are incompatible with scattered reads or writes.  There needs to be a 1:1 correspondence between reads and writes.  FXAA only became a read-modify-write algorithm after first making a backup of the search space (luminance values -> SRV<R8_UNORM>) and copying the neighbor pixel color to the work queue.  In my original implementation, both the center and neighbor pixels got pushed to the work queue, but I realized I could save memory in the work queue by just loading the center value directly from the destination buffer before overwriting it--much like alpha blending.

While I started this response by announcing you had found a "hack"--which you did--it's actually an important hack that shows the flexibility of the D3D12 API.  It generally gives you enough rope to hang yourself with.  The validation layer is there to warn you against doing bad things, but if you know what you're doing, you can sometimes ignore it.  (Please don't in a shipping game.)  And my determined nature to make read-modify-write work on a wide range of hardware has opened up the discussion internally as to how to make that happen.

I hope I've satisfied you with my answers.

Regards,
James

**Comment by pengliu916** [comment]
Thanks James, that's really very helpful. I still remember the time I try to make read-modify-write to work in dx11 where I have a 384^3 volume buffer to update every frame, doing ping-pong buffer will double the already huge memory requirement. So I end up decode and encode R32_UINT with using  "D3DX_DXGIFormatConvert.inl" during read and write in place. I think in DX12, I will try the Typed UAV load with that, and hopefully it will be faster since I don't have to do the encode and decode thing...(but given the fact that it may already been throttled by memory, so probably no improvement at all...)


Anyway, thanks so much again for such a detailed explanation and all those advises. I really appreciate it.

Peng
