### ISSUE TITLE
CopyAndBindStaleTables reclares inner loop iterator.

### ISSUE THREAD

**Issue by cmaughan** [Microsoft/DirectX-Graphics-Samples#149]
I don't have a PR, but FYI, in DynamicDescriptorHeap::DescriptorHandleCache::CopyAndBindStaleTables
the loop iterator 'i' is redeclared.

**Comment by stanard** [comment]
Thank you for informing us!  It seems to be working as designed since we're not getting rampant crashes, but it's definitely bad form and should be improved.  (In this case, the 'i' from the inner scope shadows the 'i' from the outer scope, but the inner scope does not refer to the outer scope's 'i'.)  I'll make that change now.

-James

**Comment by cmaughan** [comment]
No worries; just thought I'd mention it :) As you say, it works fine as it is!
