### ISSUE TITLE
s_TextPSO[0] vs s_TextPSO[1] and s_ShadowPSO[0] vs s_ShadowPSO[1] (HDR)

### ISSUE THREAD

**Issue by cpyburn** [Microsoft/DirectX-Graphics-Samples#153]
Not sure if this is a bug, although it could be, but I do not see any visual difference when these two states change in the mini engine.  In the code I see that the RTV format changes to a better resolution DXGI_FORMAT_B8G8R8A8_UNORM vs DXGI_FORMAT_R11G11B10_FLOAT. But visually on screen and in the graphics diagnostics I do not see any difference. If it is not visually noticeable, why did you take the time to make an HDR setting?

**Comment by stanard** [comment]
A graphics pipeline state object needs to know the pixel format of each render target it writes to.  This can affect the compilation of the pixel shader so that it exports the data in the appropriate way.  (It's sometimes hard-coded in the shader.)  So if you want to render text to a R11G11B10_FLOAT buffer, you need to have a PSO variant that exports that format.  Most of the text rendered in MiniEngine is to the UI overlay buffer, which has an alpha channel so it can be composited with the main scene buffer.  But there could easily be situations where you want to render straight to the main buffer--like to avoid a compositing step.

It may be that on your hardware the pixel format is not hard coded in the export phase of your pixel shader, and that's why you see no difference.  However, with the validation layer enabled, it should throw a warning.

(P.S.  Don't turn on the validation layer yet.  It's disabled until I push some changes to GitHub that fix a hack I've been using.)

Cheers,
James
