### ISSUE TITLE
Request: a D3D12 stereo sample

### ISSUE THREAD

**Issue by oscarbg** [Microsoft/DirectX-Graphics-Samples#18]
Hi,
Would be nice if you can add a simple stereoscopic sample using D3D12 using recommended best practices for creating the 2 back buffers,etc..
Thanks..

**Comment by bobbrow** [comment]
I can talk to the team about putting this on the backlog.  In the meantime, there is a stereoscopic sample that uses DX11 that you can reference since most of the stereo stuff is in DXGI and isn't tied to a particular version of D3D.

[Direct3D 11 Stereo Sample](https://code.msdn.microsoft.com/Direct3D-111-Simple-Stereo-9b2b61aa)

**Comment by oscarbg** [comment]
Yes I knew of the sample but somewhat lazy and hope still a compilable D3D12 stereo sample can be posted..
thanks..

**Comment by fourthskyinteractive** [comment]
The adaptation to D3D12 consists in create subresource surface for each of two back buffers? So we must iterate 4 buffers (left and right for 1st buffer, left and right for 2nd buffer)?

**Comment by bobbrow** [comment]
You don't create any resources explicitly.  You use the swap chain's resources.  You just create views off of the subresources, so the adaptation would basically involve creating RTV descriptors for each of the 4 subresources (in your example) and iterating on those (2 per frame).

**Comment by bobbrow** [comment]
Unfortunately, we're not going to have the resources to get to this in the near term.  Closing this issue for now.
