### ISSUE TITLE
MiniEngine: Is it bad to have multiple SetDynamicConstantBufferView call per frame?

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#202]
In DX11 and before, it is highly recommend to merge individual perFrame constant buffers (per object) into one giant constantbuffer and upload only once per frame. But after looking through MiniEngine's SetDynamicConstantBufferView, it seems it is safe to call SetDynamicConstantBufferView in a per object basis (if we only have couple of objects)  since LinearAllocator maintains a memory pool for us. 

So my understanding is that if we don't have massive amount of object, it won't hurt the performance if we just call SetDynamicConstantBufferView on a per object basis. 

Please correct me if I got it wrong, or there are other caveat I should be aware of. 
Thanks

**Comment by bobbrow** [comment]
I'll let James comment on the behavior of SetDynamicConstantBufferView, but UPLOAD heaps in general are not "pushed" to the GPU (i.e. they are not actively "uploaded" into GPU memory).  UPLOAD heaps reside in system memory but the GPU has access to read from those memory pages when it needs to.  These memory reads are much slower than reading from GPU memory, so if you plan to ask the GPU to read from this memory more than once(-ish), we recommend copying the data to a DEFAULT heap.  Dynamic constant buffers are only read once, so we tend to leave that data in UPLOAD heaps.

**Comment by stanard** [comment]
What's slow about using DYNAMIC resources in DX11 is how the driver handles them behind the scenes.  You are required to Map() a CPU pointer and Unmap() it so that the GPU can read it.  Behind the scenes, the driver has to dynamically allocate (upload heap) memory for you as well as handle synchronization.  If you tried to Map() the same resource again while the GPU was still reading it, the GPU would allocate a new buffer for you (i.e. rename the buffer) so long as you promised NO_OVERWRITE or DISCARD.  That was somewhat affordable but still had a pretty non-trivial cost on the driver thread.  The LinearAllocator in MiniEngine relies on DX12's "let the developer manage memory since they know best" strategy.  We pre-allocate a chunk of memory for all of these dynamic constant buffers (per CommandContext) so that the only logic needed per allocation is an overflow check and a pointer increment.  All allocations are reclaimed simultaneously with same lazy cleanup a couple frames later.  Actually, you could do something a bit like this yourself in DX11.1 using SetConstantBuffers1() which let you specify an offset into a buffer.  MiniEngine started out as HemiEngine, based on DX11, and we used SetConstantBuffers1() to get much better dynamic constant buffer performance.  Unfortunately, it was not supported on Windows 7, and so we had a hard time recommending it to developers.

One more comment:  upload heaps may be slower to read than default heaps, but it's not necessarily a bad thing to read data more than once.  It just depends on the quantity of data since it's going to restrict your bandwidth.  Also, if your reads are close enough together, it will probably still be in L2 cache.

Yet another comment:  upload heap memory is somewhat limited.  You have < 100MB to play with, so you don't want to tie it all up by permanently mapping it.  You need it for uploading resources to graphics (default) memory, and if you run out, that can have big performance implications for the driver.

**Comment by pengliu916** [comment]
Thanks James and Bob, just have a follow up question:
If upload heaps purely reside on CPU memory, why it's limited around 100MB? Is GPU only have limited addressable CPU memory? or GPU has its own structure keep track of mapped memory which limited the amount been mapped? I just don't quite understand this limitation here. 
Thanks

**Comment by stanard** [comment]
While CPU writeable, this memory actually sits on the graphics card.  I believe there is 128MB of write combined memory designated for this purpose of uploading data via the CPU.  It has historically been managed by the driver, but DX12 exposes more capabilities to the application developer.  If you get greedy or careless with this memory, you can end up choking performance.  Also, more than one app may be running, so you can't have the entire upload aperture.
