### ISSUE TITLE
Transition problem for resource shared by multithread and used in different commandlists

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#203]
It seems current MiniEngine's resource transition tracking mechanism can't handle resource shared by multithread (so will be used in different commandlist). So I just wondering what is the best approach to handle this situation.

Thanks in advance

**Comment by stanard** [comment]
Yes, this is a known limitation.  I think the only way we're going to solve this problem is by either removing the state tracking and assume the developer knows what usage state each resource should be in (coupled with the validation layer for sanity-checking) -OR- relying more heavily on the USAGE_STATE_COMMON which means "unknown state but insert a full barrier".  Your best bet for now is when building command lists in parallel to not do any resource barriers.  Bookend your command lists with a single command list that puts resources into the desired state for the subsequent built-in-parallel lists.  I know this is a key feature we need to support better, and I look forward to solving it more definitively.  Thank you.

**Comment by pengliu916** [comment]
Thanks James. Yesterday I was busy searching for state tracking after submitted this issue, and later I found out [Sebastian's video](https://www.youtube.com/watch?v=nmB2XMasz2o). In the video, the latter solution looks like a sound solution (which basically is what you said here). Since you mentioned MiniEngine is looking into this issue, it will be great if you could share your thought on this method (pros, cons or there exist better approaches)

Thanks for being patient and helpful all the time
