### ISSUE TITLE
MiniEngine: ask a color space utility question

### ISSUE THREAD

**Issue by shadercoder** [Microsoft/DirectX-Graphics-Samples#205]
in ColorSpaceUtility.hlsli 
for the input of **LinearToREC709** and  **REC709toREC2020** function, should i pass the input values in the range of 0 to 1?

thanks
peter

**Comment by stanard** [comment]
LinearToREC709 applies a gamma ramp recommended for use with HDTVs.  It should be normalized [0, 1].  I think I should rename the EOTF-style functions to "Apply..." rather than "LinearTo...".

REC709toREC2020 is a color space conversion.  Rec.709 is both a color space (defined by xy color triplets and a white point) and a gamma or transfer function.  Rec.709 is the same color space as sRGB, but sRGB defines a different gamma function.  Rec.2020 is just a color space and does not have an associated gamma function though it is usually paired with Rec.2084 for HDR displays.  Color spaces are not restricted to [0, 1].

**Comment by shadercoder** [comment]
Hi
thanks 
for the REC709toREC2020 function, because i read the this article 
[](https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.2087-0-201510-I!!PDF-E.pdf)
the page 4, it says
Colour conversion from linearly represented, normalized RGB colour signals EREGEB(Rec. 709) to linearly represented, normalized RGB colour signals EREGEB(Rec. 2020), so i quess that normalized rgb is in range 0 to 1.

thanks 
peter

**Comment by shadercoder** [comment]
article from here,
sorry
https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.2087-0-201510-I!!PDF-E.pdf

**Comment by stanard** [comment]
Yes, they are doing a conversion of SDR (standard dynamic range) colors from one space to another.  This conversion is a linear transform (matrix multiply) and should operate on linear values.  This means you should remove a gamma ramp before transformation and reapply it again afterward, if necessary.

**Comment by stanard** [comment]
So that document describes a video signal conversion, which expects that Rec.709 is not only gamma encoded but also limited range (16-235).  In MiniEngine, since all pixels are synthesized by rendering, they don't already have a gamma ramp applied, nor are they in limited range.  That all happens as the very last step as they are written to the swap chain.  In the case of Windows (currently), we write 10-bit sRGB-gamma-encoded values to a 10:10:10:2 swap chain.  I have provided other color spaces because MiniEngine has a variant for Xbox One which is not published on GitHub.  Xbox One is capable of HDTV output as well as HDR output.
