### ISSUE TITLE
MiniEngine: Possible error in CommandSignature

### ISSUE THREAD

**Issue by baldurk** [Microsoft/DirectX-Graphics-Samples#207]
While implementing support for ExecuteIndirect I was looking at the code in `CommandSignature.cpp` / `CommandSignature.h` and I think the handling for root constant setting is slightly wrong.

The `Constant()` function on `IndirectParameter` allows setting multiple values a la `Set*Root32BitConstants`, which I believe means the data in the argument buffer is variable length according to the `Num32BitValuesToSet` parameter. The calculation in `Finalize()` though for the byte stride seems to assume only one 32-bit constant will be in the argument buffer:

``` cpp
            case D3D12_INDIRECT_ARGUMENT_TYPE_CONSTANT:
                RequiresRootSignature = true;
                ByteStride += 4;
                break;
```

It should probably be something like:

``` cpp
            case D3D12_INDIRECT_ARGUMENT_TYPE_CONSTANT:
                RequiresRootSignature = true;
                ByteStride += sizeof(UINT) * m_ParamArray[i].Constant.Num32BitValuesToSet;
                break;
```

I don't have a repro case/test case, I just saw this by inspection and it looked wrong.

**Comment by stanard** [comment]
I think you're right.  This got overlooked because we didn't test very many command signatures.  (We only needed to re-implement DrawIndirect() and DispatchIndirect().)  I'm trying to confirm in the documentation, but it makes sense that each indirect command stream would need space for all the constants.  Thanks for letting us know.  I'll try to to get this and a couple other fixes out to GitHub shortly.

**Comment by stanard** [comment]
This bug fix was included in the recent Creators Update push.
