### ISSUE TITLE
MostDetailedMip and ResourceMinLODClamp use not covered

### ISSUE THREAD

**Issue by howprice** [Microsoft/DirectX-Graphics-Samples#215]
It would be useful if one of the examples could use MostDetailedMip and ResourceMinLODClamp (D3D12_TEX2D_SRV) . From the [Direct3D Reference documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/dn770434(v=vs.85).aspx) is is not clear why there are two distinct values and how they are supposed to be used.

For example in a mipmap streaming system in which the top mip for a texture is not loaded, would MostDetailedMip  or ResourceMinLODClamp or both be set to 1 (1.0)?

**Comment by stanard** [comment]
I hope someone else comments to confirm my theory.  Since you can create different views on a resource, I think the "MostDetailedMip" field is to say "Treat this mip as level 0.  There might be more detailed mips in the resource, but I want to ignore them."  So if MostDetailedMip is level 2, using this SRV you would actually refer to it as a level 0.  The ResourceMinLODClamp is going to be relative to your new indexing scheme.  And it supports fractional values.  You could say, "don't access higher than mip level 0.5", and all of your trilinear or anisotropic filters would clamp texturing to Mip >= 0.5.  In the original resource, that would actually be level 2.5.

**Comment by stanard** [comment]
Okay, we had a discussion, and my theory wasn't correct.  MostDetailedMip is kind of a vestigial leftover from D3D11.  For compatibility reasons you can still specify it separately from ResourceMinLODClamp, but now it's part of the view descriptor.  So it's a little redundant.  But it does not change the indexing on the mip levels.  In my previous example, with MostDetailedMip=2, you might want ResourceMinLODClamp=2.5.

**Comment by howprice** [comment]
Thanks very much for the info.
