### ISSUE TITLE
Compiling shaders in Mini Engine

### ISSUE THREAD

**Issue by MichaelWei1990** [Microsoft/DirectX-Graphics-Samples#216]
May I ask how to compile the shaders in Mini Engine? I know this is probably not the right place to post this question, but I really hope someone could help me or point me in the correct direction. 

I added the ModelViewer shader hlsl files (VS and PS) to Mini Engine solution and they can be built, however, the compiled headers are not the same even the codes in shaders are exactly the same and they cause a problem in rendering with few black patches. Therefore, I am wondering if I did not configure the shaders compiler properties. I tried Shader Model 5.1 (/5_1) and 5.0 (/5_0) in HLSL Compiler‘s General, but neither of them generated the correct header files. 

Thank you for answering my question.

**Comment by bobbrow** [comment]
Is there a problem with compiling the shaders, or with how they behave?  Sorry, it's unclear to me exactly what problem you are experiencing.  I'm not sure why you would need to add any shader files to the solution.  Everything should already be set up in the version committed to our repo.

**Comment by MichaelWei1990** [comment]
The solution works perfectly fine with the existing files and shaders. I am exploring the project and the problem happens if I change in the hlsl file and compile the shaders. I am wondering if I did anything wrong in the HLSL compiler settings. I would appreciate if you could share the setting properties with me, thanks.

**Comment by stanard** [comment]
The shaders in MiniEngine compile to header files so that the binaries can be linked into your program and do not need to be loaded individually.  The default shader settings on the project root are CS with SM5.0.  If you add a VS or PS, you need to change the shader type in the settings.  The header files are written out to the Build_VS14 folder that is at the root level along with Core.  Look for the CompiledShaders folder.
