### ISSUE TITLE
”MiniEngine“ How to render multiple models？

### ISSUE THREAD

**Issue by LigaLiao** [Microsoft/DirectX-Graphics-Samples#231]
I'm trying to use “gfxContext.PIXBeginEvent&gfxContext.PIXEndEvent”  to render multiple models.
But this is not feasible.
First-model is not displayed.

**Comment by LigaLiao** [comment]
I mean in "MiniEngine" how to render multiple models.

**Comment by stanard** [comment]
ModelViewer is poorly named.  It was originally conceived to load different models, but it quickly turned into just the "Sponza (Atrium) Viewer".  We have a very poor model and texture pipeline, but we think that the ModelViewer project teaches a lot of the basics needed for writing a truly data-driven content viewer.

PIXBeginEvent() and PIXEndEvent() are only used for debugging and profiling (and are not used explicitly very often).  You might be looking for GraphicsContext::Begin() and GraphicsContext::Finish().  This is how you create a command list and then execute it.  But you can draw more than one model in the same command list.  Sponza, itself, is composed of several different meshes and involves texture changes.  If you are to draw other models along with or instead of Sponza, you need to draw them during the ZPrePass, the shadow phase, and the final color pass.

**Comment by LigaLiao** [comment]
Thanks ！
