### ISSUE TITLE
ESRAM

### ISSUE THREAD

**Issue by sourcecodewizard** [microsoft/DirectX-Graphics-Samples#232]
Sorry ahead if this is not the right place to ask this, please redirect.....

The mini engine has an ESRAM allocator header but the code is mostly empty.

I read another issue from back in march that said there were licensing issues so the GitHub version does not have it enabled.  

I trying to allocated a simple texture2D using ESRAM when running on the xbox.  I'm not using the mini engine just a texture2d.  Any suggestions on where I can get working sample code that does this?

btw the mini engine is nicely done, ran right out of the box and looks great!

thanks
Paul

**Comment by sourcecodewizard** [comment]
Chuck,I downloaded the MiniEngine source directly from GDNP and it does not appear to address ESRAM allocation anywhere except for a mostly empty class header. Am I missing something?
thanks
source follows:

class EsramAllocator


{

public:


 EsramAllocator() {}

 void PushStack() {}
 void PopStack() {}
 D3D12_GPU_VIRTUAL_ADDRESS Alloc( size_t size, size_t align, const std::wstring& bufferName )


 {

 (size); (align); (bufferName);
 return D3D12_GPU_VIRTUAL_ADDRESS_UNKNOWN;


 }

 intptr_t SizeOfFreeSpace( void ) const


 {

 return 0;


 }
};

**Comment by stanard** [comment]
The EsramAllocator should be fully implemented in the MiniEngine on GDNP (developer.xboxlive.com).  The header file uses #defines to distinguish between Win32 Desktop and Xbox One ERA.  The CPP is omitted entirely for the GitHub distribution.  The problem with the GDNP distribution is that it MiniEngine doesn't have a regular release schedule.  I believe it has only been linked with an Xfest talk from last year.  I sincerely hope to update both releases very soon to get them back in sync and to push out a lot of recent improvements.

**Comment by sourcecodewizard** [comment]
any guidance on how to get an account on that portal?
or could I get a copy of EsramAllocator.cpp?
I really only need to know the DirectX settings/calls needed to specify esram when creating a texture2D so I can do some profiling.
Any guidance would be greatly appreciated.
nice work on that engine btw

**Comment by stanard** [comment]
Assuming you work for a game studio, you should talk to your producer or dev manager.  If you _are_ that person, you should talk to your studio's account manager directly.  I can't provide the code on GitHub because it requires a signed NDA.

The APIs involved require managing your own virtual memory with pages backed by ESRAM.  Then you can use placement create functions for providing your own memory to the resource.  The EsramAllocator itself is a stack-based allocator that depends on the scope of a resource to determine when its memory can be reused.  This is the reason why so many buffers/targets are allocated in BufferManager.cpp--so they can coordinate their shared ESRAM usage.  That must seem weird when viewed from the perspective of a Windows-only release.

**Comment by sourcecodewizard** [comment]
Yea I noticed the esram.PushStack() calls.  From your description it sounds similar to how I'm managing constant buffers with a local PC data structure and an identical structure to access the data in the shader.  I'm hoping to just keep the data resident and not have to do a lot of per frame buffer manipulation but we'll see....
I am a solo developer building a game directly on DX11 targeted for the Xbox one (then PC a few months later).I've got 2 more years of (my own) funding to get it released so this is not a major issue yet.  But I do have a working terrain model that will account for a substantial portion of my framerate and it currently does a lot of sampling on a 16 MB heightmap so I thought that would be a perfect candidate for ESRAM since it will always be rendered and still allow just enough room (maybe) for a couple 1080p display buffers.  
I have no problem with the NDA provided I can use enough of the code to use the ESRAM.
I'm reasonably fluent in DX so any working sample code or even snippets with the actual DX descrips&calls should get me there.  It's just that I cannot find anything related to ESRAM throughout the DX official MS documentation.  And googling for anything ESRAM gives a flood of Xbox marketing material but no dev material.
Any help in pointing me in the right direction would be greatly appreciated.thanks

**Comment by Triang3l** [comment]
@stanard @walbourn With the Fall Creators Update allowing UWP Direct3D 12 games to use expanded resources, I think giving ESRAM access to UWP game developers would greatly help Xbox One to become **the** platform for independent game developers.

As I understand, so far there's no way for UWP games to access the ESRAM (or am I wrong?). UWP seems to be the quickest way for indie developers to jump into Xbox One development, and with ESRAM access, they will be able to adapt their rendering architecture, shaders and content to the actual performance of the Xbox One and the Xbox One S at the earliest stages of development, before it becomes too time-consuming to perform large-scale optimizations or to reverse content quality reduction — and then upgrade to ID@Xbox or a full license with a beautiful and a well-optimized game. Easy prototyping and testing without barriers is what makes the PC an attractive platform for independent developers.

I wonder, are there any obstacles preventing ESRAM usage in UWP apps from the technical point of view?

In Direct3D 12, I have no idea how ESRAM access is actually implemented, but I'd imagine the ESRAM being exposed as a special D3D12_HEAP_PROPERTIES configuration in a call to ID3D12Device::CreateHeap, which does all the VirtualAlloc work (also wondering, was mapping ESRAM required just for CreateBuffer/CreateTexture calls, or did nobody simply use them and that's why mapping is so important?) behind the scenes and creates a heap that you can create placed resources in. I think this way, coupled with aliasing barriers already there in D3D12, would cover pretty much all ESRAM use cases (maybe with the exception of combined ESRAM and DRAM usage for portions of a single resource) and also be the easiest to use by game developers coming from Windows.

What appears to be a potential obstacle is the ownership of the ESRAM by processes. However, if I understand correctly, UWP games can't run side-by-side with other non-UWP or UWP games, so switching between contexts of processes using the ESRAM shouldn't happen at all.

So, is there any possibility of indies trying out the platform to get something like an ID3D12Device4::CreateHeap for the ESRAM?

**Comment by Triang3l** [comment]
No hardware LZ and JPEG access is not a big issue, but the ESRAM is a huge factor in frame time and image quality.

**Comment by stanard** [comment]
While I can't discuss our technical roadmap for UWP on Xbox, I want you to know that we have been thinking about these issues.  It sounds like you would also be a candidate for the ID@Xbox program where we help indie developers get their game ideas onto the Xbox.  While you can already target UWP on Xbox, there are *reasons* why that can't be as optimal as targeting our Xbox game OS directly.  Apps on Xbox are either the dedicated game app (like Gears of War) or a system app like the Achievements toast app.  Obviously, the game app gets the lion's share of system resources.  When there is no game app running, the other apps have more resources to share, but they still must share them fairly and no one knows which is more important.  But for accessing ESRAM, that's the exclusive right of the dedicated game app.  If you were using ESRAM in a system app, and then the game app started up, the system app would lose its ESRAM or have to exit.

So if you want to optimally program Xbox, you should ask to join the ID@Xbox program.  Another option is you could buy a Scorpio to play with, and ESRAM won't be a concern.  Also, it's fast enough to make up for not having as many resources as the dedicated game app.

**Comment by Triang3l** [comment]
Of course system apps and UWP non-game apps wouldn't need ESRAM access or expanded resources at all, but are UWP game apps with expanded resources treated very differently than XDK games? I don't have an Xbox yet unfortunately, so I can't check by myself, but I was suggesting giving ESRAM only to UWP games.

**Comment by walbourn** [comment]
It's also worth noting that ESRAM doesn't exist on Xbox One X. Therefore, any use of ESRAM would require different codepaths on Xbox One/Xbox One S vs. Xbox One X. As such, it's likely any use of ESRAM would be done automatically rather than explicitly exposed.


-Chuck Walbourn
Senior SDE
http://blogs.msdn.com/chuckw
________________________________
