### ISSUE TITLE
Bitonic Sort details

### ISSUE THREAD

**Issue by howprice** [Microsoft/DirectX-Graphics-Samples#235]
Hi. Would it be possible to provide some more details on the bitonic sort routines used in the particle effects manager?

Specifically I'd like to know what constraints there are on the number of elements (particles) to be sorted. I realise that the particle index is stored in 18bits of the sort key so MAX_TOTAL_PARTICLES == 1<<18 (256*1024). But what is the minimum number of particles that can be used (min number of elements in the sort buffer). From the shaders looks like it might be 2048. How about intermediate values? Do they have to be a multiple of 2048?

Also, will the k loop in BitonicSort() have to be modified buffer num elements < MAX_TOTAL_PARTICLES?

Is the Bitonic Sort algorithm used based on a reference implementation elsewhere, or a paper perhaps?

Many thanks for any information you can provide.

**Comment by stanard** [comment]
At one time this was all clear in my head, but it's been a while.  As I recall, there is no minimum sort size, but clusters of 2048 are pre-sorted before the multi-dispatch bitonic sort.  (See ParticlePreSortCS.hlsl.)  When there is less than 2048, the list is padded with zeros, and no further dispatches would be required.

**Comment by stanard** [comment]
I recently pushed a generalized version of the bitonic sort.  (And I optimized it further.)  It now supports non-power-of-two list lengths.  If you look in Core/BitonicSort.h you will find many comments that describe the overall system, and there are comments sprinkled throughout the shaders to discuss specific details.

While non-power-of-two list sizes are now possible--with no alignment whatsoever--if you implement your own pre-sort shader, you should follow the pattern set out by ParticlePreSortCS.hlsl and Bitonic32PreSortCS.hlsl.  Since they have thread group sizes of 1024, and sort 2048 elements, the list gets padded up to 2048 elements in groupshared memory.  This only affects the last group in the list.  The reason for that is to avoid additional logic in the inner loop.

The original bitonic sort algorithm sorted even groups in ascending order and odd groups in descending order.  The group size was determined by the outer loop parameter 'k'.  The idea is that you sort groups of larger and larger size until ultimately your group size is the entire list.  But because of the odd/even nature of the sort, you had to have powers of two list sizes, and items moved a lot more frequently.

A variation on this algorithm inverts the sort for odd groups so that both odd and even sort in ascending order.  Now all groups continue to sort in the same direction, and because of this, you never have to test the pad elements at the end of the list, because they are guaranteed to always be greater than or equal to everything else, so they stay put.

I don't want to go into too much detail explaining the algorithm here, but please pull down the code and see for yourself!

Regards,
James

**Comment by howprice** [comment]
Hi James. That's great. Many thanks for the information and update. I'll check it out ASAP. I hope I didn't derail you from other work.

**Comment by stanard** [comment]
No, I actually revisited this code for my own purposes.  After looking through open issues, I remembered you had asked about it.  So it just worked out well.  :-)
