### ISSUE TITLE
MiniEngine: Parallel Drawcalls

### ISSUE THREAD

**Issue by blippyblips** [microsoft/DirectX-Graphics-Samples#238]
Hi,

Wondering if there's any progress on either parallel work submission or even just a BundleContext? If not, is there any documentation or thoughts you've collected on how you would go about adding these features?
If yes then any chance of a beta branch to test it out?

Also curious what other features you have planned over Q1 2017 if there's a spot to read about current WIP and near future things.

Thanks

**Comment by stanard** [comment]
We tend to add things to MiniEngine as needed, and unfortunately, we haven't had a need to parallelize command list generation yet.  It's high on our interests, but other things take precedent, especially since developing MiniEngine is no one's full time job.

However, I am expecting to post a massive update to MiniEngine on GitHub today.  Here is the upcoming changelist:  

New temporal antialiasing (TAA) implementation
Camera controller now adjusts speed relative to pixel zoom level
Added Intel SSE-optimized code for generating colors as R11G11B10_FLOAT on the CPU
Added support for creating MSAA color buffers
Added support for dynamic sampler descriptor heaps
Encapsulated dynamic upload heaps (DynamicUploadBuffer) for passing data from CPU to GPU, e.g. dynamic vertex buffers
Removed SamplerDescription in favor of raw D3D12_CPU_DESCRIPTOR_HANDLE
Removed CD3D12_SHADER_BYTECODE helper struct in favor of D3DX12.h: CD3DX12_SHADER_BYTECODE
Added support for very large LinearAllocator pages to be used with temporary uploads
Added integer Log2() to Math utility functions
Reduced alignment of Matrix4 to 16 bytes from 64
Renamed various shader utility functions to disambiguate gamma ramps (e.g. sRGB) from linear color spaces (e.g. XYZ)
Added LUV conversion routines for packing HDR colors precisely into 32-bits
Added Forward+ lighting to ModelViewer.  (Lights are randomly placed.)
Improved speed of the ZPrePass by isolating alpha tested materials into their own pass
Changed video adapter selection logic to find that with the most dedicated video memory
Various code quality fixes

Soon after this update, the Forward+ lighting will be improved to take advantage of the new shader compiler and SM 6.0.  The new wave intrinsics are especially potent!

-James

**Comment by blippyblips** [comment]
Looking forward to seeing the updates

Do you have any thoughts or notes on how you would go about implementing bundles and fixing multi threaded command list generation?
Do you know of any issues that would be immediately blocking when trying to add either?

Thanks again

**Comment by stanard** [comment]
For bundles, I think I'd subclass CommandContext and set the m_Type field to D3D12_COMMAND_LIST_TYPE_BUNDLE.  Then I'd override all functions that shouldn't be exposed for bundles by making them private.  I'd also have to add a method to CommandContext so that it can invoke a Bundle.  Because bundles are reusable, I'd  have to circumvent the ID3D12CommandList* and ID3D12CommandAllocator* recycling system.  Or instead, it might be worthwhile to just make a separate class just for bundles to not blur the lines between command lists and bundles.

The challenge with multi-threaded CL generation is the resource barriers, and specifically resource transitions.  We've added a COMMON resource state that I think is supposed to be like "I don't know", and that could be useful.  You see, when you are building your command lists in parallel you don't necessarily know what state a resource will end up being when it's time for your new command list to run.  You could forbid resource transitions inside of parallel command lists.  Or you could always end a command list by putting certain resources into a known state.  But in its simplicity, MiniEngine tracks the resource state so that you don't have to supply it every time you issue a transition.  But this shadow variable is not thread safe, so if you want to do resource transitions on parallel command lists, you would need to overhaul that state tracking mechanism.

I think that you would get the most bang for the buck if you break up very long command lists without state transitions (like the entire Depth or Color passes) into multiple lists.  But for things like reflection or shadow map rendering, where you set the resource as a target and conclude by making it a shader resource, you probably don't want to split those up.  You could, however, generate multiple shadow buffers in parallel, each on its own command list.
