### ISSUE TITLE
D3D12 online docs: bug in D3D12_GPU/CPU_DESCRIPTOR_HANDLE

### ISSUE THREAD

**Issue by floooh** [Microsoft/DirectX-Graphics-Samples#25]
[Update: fixed link]

A minor, but quite confusing doc bug in D3D12_GPU_DESCRIPTOR_HANDLE and D3D12_CPU_DESCRIPTOR_HANDLE, says that the ptr element is "The size, in bytes, of the block of memory that the GPU descriptor handle points to."

Shouldn't this be something like "a cpu/gpu accessible opaque pointer to a descriptor in a descriptor heap"?

See:

https://msdn.microsoft.com/en-us/library/windows/desktop/dn859391(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/dn859369(v=vs.85).aspx

Is there a better place for reporting doc bugs?

**Comment by weltkante** [comment]
You can report msdn doc bugs on the page where the bug is, via the "was this page helpful" buttons to give feedback (not by leaving a comment on that page!). In my experience it will then be fixed. Unfortunately you won't get any feedback about it, in particular when your description wasn't detailed enough for them to understand the problem they can't fix it but they can't ask you about more details either.

Whether this is "better" than reporting it here I don't know.

**Comment by floooh** [comment]
Ok I did that too. Having a public bug tracker like Firefox or Chrome have, where you get notified by mail when new comments are attached or the state of the ticket changes would be very helpful for the D3D12 docs, they seem to be written in a bit of a hurry ;)

**Comment by bobbrow** [comment]
I can forward anything reported here on to the documentation team, though I am following up with them to see how often they go through the feedback received through MSDN documentation pages.

**Comment by bobbrow** [comment]
I haven't seen any bugs filed on our side yet so I went ahead and filed them.  Once the bugs are filed, our writer generally addresses them pretty quickly, but I don't have a lot of insight into their schedules for publishing updates to MSDN.  Could be a couple of weeks before the changes go live.

**Comment by floooh** [comment]
Thanks!
