### ISSUE TITLE
MiniEngine: Frustum and intersection tests

### ISSUE THREAD

**Issue by blippyblips** [Microsoft/DirectX-Graphics-Samples#258]
Noticed that the included frustum plane or sphere intersection don't seem to be working correctly.

Even a simple case of intersect against BoundingSphere(0,0,0,100) doesn't always give correct results.

Also saw that they're not used anywhere so may not be important but might be nice to have them looked at.

**Comment by stanard** [comment]
You said "doesn't always give correct results".  Can you be more specific?  I am suspecting a misplaced sign causing a plane to face the opposite direction or some similar problem.  I'll try to look into it today.

Thanks,
James

**Comment by blippyblips** [comment]
Yeah it seems like it's something with the camera transformations as pointing a camera towards a location from 1 side vs another can return two different results, as well as the bottom and right planes don't seem to extent as far as they should.

I had a quick look and 2 things that seemed odd to me was that BoundingPlane normals aren't normalized for camera frustum planes and the frustum seems to be created from the projection matrix rather then the view projection as seems to be more common.

**Comment by stanard** [comment]
I've been fixing some other bugs, but that is good intel.  If the planes aren't normalized, it would give incorrect sphere checks because the distance from sphere center could be incorrectly determined.

**Comment by blippyblips** [comment]
Looking forward to update later. If you have the chance and time it would be great if you could throw in a check for the BoundingBox too.

**Comment by stanard** [comment]
I believe I've found and fixed three bugs related to the BoundingPlane class.

1) GetNormal() was scaling the normal by 1/D.  (Treating it like a Vector4 -> Vector3 conversion.)
2) When transforming the view-space frustum to world-space, the inverse-transpose of the OrthogonalTransform was incorrect.  This messed up the world-space bounding planes.
3) There was a bug in the "OrthogonalTransform * BoundingPlane" function.

I fixed 1 and 3, and it made 2 unnecessary to fix.  (It's more efficient to use the OrthogonalTransform directly rather than generate a Matrix4.)  I'll push these changes soon.

**Comment by blippyblips** [comment]
Great stuff

If you want to throw in a BBox check with the update; here's a implementation to match the very simple BoundingBox that is in MiniEngine already (Inside model.h i think?).

bool IntersectAAB(BoundingBox aabb)
{
	auto min = aabb.min;
	auto max = aabb.max;

	for (int i = 0; i < 6; i++) {
		if (m_FrustumPlanes[i].DistanceFromPoint({min.GetX(), min.GetY(), min.GetZ()}) > 0.0f)continue;
		if (m_FrustumPlanes[i].DistanceFromPoint({min.GetX(), min.GetY(), max.GetZ()}) > 0.0f)continue;
		if (m_FrustumPlanes[i].DistanceFromPoint({min.GetX(), max.GetY(), min.GetZ()}) > 0.0f)continue;
		if (m_FrustumPlanes[i].DistanceFromPoint({min.GetX(), max.GetY(), max.GetZ()}) > 0.0f)continue;
		if (m_FrustumPlanes[i].DistanceFromPoint({max.GetX(), min.GetY(), min.GetZ()}) > 0.0f)continue;
		if (m_FrustumPlanes[i].DistanceFromPoint({max.GetX(), min.GetY(), max.GetZ()}) > 0.0f)continue;
		if (m_FrustumPlanes[i].DistanceFromPoint({max.GetX(), max.GetY(), min.GetZ()}) > 0.0f)continue;
		if (m_FrustumPlanes[i].DistanceFromPoint({max.GetX(), max.GetY(), max.GetZ()}) > 0.0f)continue;
		return false;
	}
	return true;
}

**Comment by stanard** [comment]
Thanks for the contribution, but I found a way to improve it a little.  :-)

Instead of testing all 8 points per plane, you can just test the point farthest away in the direction of the plane's normal.  Think of it like a ray entering a box.  If it's heading to the right, it comes in from the left, so the right-most bound is farthest away.  I.e. positive directions test the max, and negative directions test the min.

`Vector3 farCorner = Select(minBound, maxBound, m_FrustumPlanes[i].GetNormal() > Vector3(kZero));`
`if (m_FrustumPlanes[i].DistanceFromPoint(farCorner) < 0.0f) return false;`

P.S. I had trouble inserting code.  It kept deleting my newlines, so I reduced it to as few lines as possible.

**Comment by stanard** [comment]
I wanted to notify you that I just pushed the code fixes.  Cheers!
