### ISSUE TITLE
Error on shutdown

### ISSUE THREAD

**Issue by cmaughan** [Microsoft/DirectX-Graphics-Samples#261]
With the master branch, I see this in the debug output:

D3D12 ERROR: ID3D12CommandQueue::<final-release>: A Command Queue (0x0000024E5EDA8D00:'Unnamed ID3D12CommandQueue Object') is being final-released while still in use by the GPU.  This is invalid and can lead to application instability. [ EXECUTION ERROR #921: OBJECT_DELETED_WHILE_STILL_IN_USE]

It happens at this point, when the final display plane is destroyed.  Something to do with the swap chain's reference to the command queue, but I'm not sure what...
    for (UINT i = 0; i < SWAP_CHAIN_BUFFER_COUNT; ++i)
        g_DisplayPlane[i].Destroy();

**Comment by stanard** [comment]
Thank you for bringing this to our attention.  I'll take a look, but I'm suspecting it has to do with the order of terminating resources.  g_DisplayPlane is a ColorBuffer (RTV & SRV) attached to one of the swap chain buffers.  While D3D has validation to make sure the application cleans up responsibly at shutdown, once the executable is destroyed, all resources are purged automatically.

**Comment by stanard** [comment]
I wanted to notify you that this issue has been fixed with my recent push.  The problem was that I had assumed only the application which creates a command queue could issue work on it (related to the app), but I discovered the system does so as well for the purposes of Present operations.  To fix the bug, I incremented the fence counter and explicitly signaled it again before waiting on it.  This flushes all work currently in flight.

**Comment by cmaughan** [comment]
Great stuff, thanks.!

**Comment by ACskyline** [comment]
Thanks! Can't believe this thread is the only relevant one that came up when googling this problem.

**Comment by matt77hias** [comment]
@stanard are these implicit/hidden submissions only possible for `Present` operations for `D3D12_COMMAND_LIST_TYPE_DIRECT`?

**Comment by ACskyline** [comment]
Sorry Matthias, I don't think I can answer this question. 
But I feel like this only applies to render command queues because OS probably does not use compute or copy queues.     On Sunday, September 8, 2019, 06:14:54 AM EDT, Matthias Moulin <notifications@github.com> wrote:  
 
 
@stanard are these implicit/hidden submissions only possible for Present operations for D3D12_COMMAND_LIST_TYPE_DIRECT?

**Comment by jenatali** [comment]
@matt77hias, yes these are only possible on DIRECT queues.

**Comment by matt77hias** [comment]
> @matt77hias, yes these are only possible on DIRECT queues.

Because that is the type of command queue, one needs to bind to the swap chain? But stated differently, it is not possible that the system somehow hijacks queues for which I did not pass some pointers around?

**Comment by stanard** [comment]
@matt77hias, from what I understand, the "implicit/hidden submissions" are initiated by transitioning your display buffer to D3D12_RESOURCE_STATE_PRESENT.  This transition barrier can only be issued on the Graphics Queue.

**Comment by jenatali** [comment]
It is done by calling Present on a swapchain, not the transition. Some work may be submitted to the queue where the swapchain was created. And swapchains can only be created by DIRECT queues. DXGI does not "hijack" queues that you didn't ask it to use.

**Comment by matt77hias** [comment]
Thanks all for the clarifications 👍

**Comment by tom-seddon** [comment]
For future reference, looks like the recent push in question was 223f2606608f8f2c3ef2f50376670889e29fbffa 

--Tom
