### ISSUE TITLE
The Requirements(Windows10,VS2015)

### ISSUE THREAD

**Issue by unnamedProfile** [Microsoft/DirectX-Graphics-Samples#27]
Can i use this samples in Visual Studio 2010, Windows 7?
I doesn't Have Windows 10 or Visual studio 2015.

**Comment by alessiot89** [comment]
D3D12 runtimes require WDDM 2.0 which requires Windows 10.
Remember you can get Windows 10 for free if you upgrade from a legit Windows 7/8/8.1 installation.

As for Visual Studio 2010, the API should work with it, but I am not sure about this samples code since VS2010 doesn't have a good C++11 support.
Remember that you can get VS Community for free, which is more or less the same as VS Professional but with a different license. I recommend you VS 2015 Community. You can also use Visual Studio Express Desktop Edition, of course it comes with strongest feature limitations.

**Comment by unnamedProfile** [comment]
Thank You! for your information.
