### ISSUE TITLE
Reset of CommandList and CommandAllocator

### ISSUE THREAD

**Issue by subb** [Microsoft/DirectX-Graphics-Samples#270]
Hi there,
This is not a issue with the samples per se, more of an question about DX12. Hopefully this is an OK place to ask this.

I'm trying to figure out from the documentation and samples the internal working of command lists and command allocators, especially with respect to their reset functions.

Specifically, I'm wondering if the following use case is valid :
```
commandList->Reset(commandAllocator, nullptr);
// record some commands
commandList->Close();
ID3D12CommandList* commandLists[] = { m_commandList };
commandQueue->ExecuteCommandLists(1, commandLists);

commandList->Reset(commandAllocator, nullptr); // same command list, same allocator
// record other commands
```

The documentation seems to indicate that this is valid, but I'm not sure. It would mean that either commands are copied somewhere once ExecuteCommandLists is called, or the reset request a new "block" from the allocator. But, from my (possibly incorrect) tests, doing this is a loop without resetting the allocator doesn't cause memory usage to grow. I also doesn't cause the debug layer to scream (unlike calling reset on the allocator), which leaves me a bit confused.

So my question is : What happens exactly when I call reset on a command list and why does it ask for a command allocator? 

Thanks!

**Comment by stanard** [comment]
An ID3D12CommandList is pretty small.  It points to a command allocator, the first page of commands, the current page, and the write pointer.  The pages are joined like a linked list.  It's the allocator that provides the pages as needed when the write pointer is about to run past the end of a page.  Closing the command list is necessary to say that the current write pointer is the end of all commands.  Now the command list points to the start and end of the commands, and the command queue can execute that series of commands.  This is a small amount of information that can be copied by the command queue, letting you immediately reuse the ID3D12CommandList object.  The allocator can also be reused, because it will provide different memory pages for the newly reset command list.  So the Reset() call gets a new blank command page, and sets the write pointer to the start of it.

**Comment by subb** [comment]
Thanks for the reply.
I realized there was an error in my test (of course). Resetting the CommandList without resetting the CommandAllocator increase memory usage, as expected. Now everything make sense.

Thanks again.
