### ISSUE TITLE
Matrix3 memeory issue

### ISSUE THREAD

**Issue by zjxeditor** [microsoft/DirectX-Graphics-Samples#289]
In the math library of MiniEngine project, please pay attention to Matrix3.

The comment says: " Represents a 3x3 matrix while occuping a 4x4 memory footprint." However, the alignment settings is "__declspec(align(16))" and data members are declared as "Vector3 m_mat[3]".
I think the memory footprint is 3x4 rather than 4x4. If it is true, the implicit convertion from "Matrix3" to "XMMATRIX" is pretty dangerous. The extra 16 bytes memory is fetched from other address. So, why the code is runnable? Dive into the code, only read operation is performed. The extra memory will no be modified.

If what I think is true, this is a tricky but dangerous operation. Hope for reply, thanks.

**Comment by stanard** [comment]
You are right.  There is something off about this code.  The untrue comment ("4x4 memory footprint") coupled with the cast to XMMATRIX suggests to me that once upon a time this class was identical to Matrix4 but ignored the 3rd row and 3rd column.  I don't think the class is bad, but the comment needs to be fixed, and I will see if any code actually depends on a cast to XMMATRIX.  Keep in mind that the cast does not return a reference, so it would be copying invalid memory but not making it writeable.

**Comment by weltkante** [comment]
Can't reading invalid memory turn into an access violation or other bad stuff (e.g. triggering guard pages) when it happens to be close to the boundary of a mapped address space segment? Certainly sounds like bad practice and not something people should copy from the examples without being aware of all the lurking dangers.

**Comment by stanard** [comment]
The worst that could happen is a page fault, but in the very unlikely event that the Matrix3 is right at the end of a virtual memory page, the undefined fourth vector probably won't be read anyway.  The reason for the cast from Matrix3 to XMMATRIX is because DirectXMath doesn't have other matrix types.  So functions for rotating a normal, for instance, still use the 4x4 matrix but only look at the relevant 3x3 part.  You can guarantee that you don't read invalid memory by replacing the cast method with this:

`INLINE operator XMMATRIX() const { return XMMATRIX(m_mat[0], m_mat[1], m_mat[2], XMVectorZero()); }`

When I make my next commit, I'll include this change.  Thank you.

**Comment by walbourn** [comment]
As the author of [DirectXMath](https://github.com/Microsoft/DirectXMath), I'll note that in theory you really want that last row to be [0 0 0 1] instead of [0 0 0 0]. You could use the built-in vector constant ``g_XMIentityR3``.

A safer solution might also be to do the following:

    INLINE operator XMMATRIX() const { return XMLoadFloat3x3(reinterpret_cast<const XMFLOAT3X3*>(this)); }

**Comment by zjxeditor** [comment]
Yes, I think that we should make things clear. Fetch data from extra memory space is really a bad practice, though it may be more efficient. Code is ok due to the copy of the converted value. Definitely, both solutions are workable which are provided by @stanard and @walbourn .

**Comment by stanard** [comment]
The intention of the cast from Matrix3 to XMMATRIX is to interoperate with the Matrix3-style functions in DirectXMath.  These functions don't load the fourth row (and ignore the fourth column).  The Matrix3 class deliberately leaves the fourth element of each vector undefined, knowing that they should not be touched or trusted.  Both of these are intended to produce fast-but-unsafe code.  It is up to the user to be aware of the restrictions. To get a safe upgrade to Matrix4 with zeros in all undefined entries and a one in the [3][3] position, you can use the Matrix4::Matrix4(Matrix3) constructor.  So the safest canonical way to convert a Matrix3 to an XMMATRIX would be:

`INLINE operator XMMATRIX() const { return (XMMATRIX)Matrix4(*this); }`

But if you want that, you can simply cast your Matrix3 to Matrix4 and get an implicit cast to XMMATRIX.  This code was also written before MSVC had support for explicit cast declarations which requires you to force a cast to XMMATRIX and is safer in that this makes it a deliberate choice rather than an accident.  I will see if I can make this cast explicit to reduce debugging headaches.
