### ISSUE TITLE
XAML / WPF interop classes creation

### ISSUE THREAD

**Issue by mprevot** [microsoft/DirectX-Graphics-Samples#318]
Would it be possible to create Interop classes so it were possible to add a D3DX12image in XAML for WPF development ? And have a simple sample achieving this ?

Maybe it some code from https://github.com/Microsoft/WPFDXInterop would be relevant.

Thanks !

**Comment by maximebl** [comment]
It is possible to use UWP and XAML together with DirectX12 but I'm not sure about WPF. You can find an example here which uses C++/CX as its language projection for the windows runtime:
[](https://github.com/Microsoft/DirectX-Graphics-Samples/tree/feature_xaml_template/Templates/DirectX12XamlApp)

It's also possible to use the newer CppWinRT instead of C++/CX. You can find an example here: 
[](https://github.com/maximebl/dx12_xaml_template)
