### ISSUE TITLE
D3D12RaytracingMiniEngineSample - Inconsistent performance when cycling through different rendering modes

### ISSUE THREAD

**Issue by Woking-34** [Microsoft/DirectX-Graphics-Samples#323]
Hi,

I have a predefined viewpoint in the Sponza scene.

When I launch the sample and select [7] Hybrid pass I get around 20ms gpu time and 101 mrays/sec. If I jump to the [6] Fully-raytraced pass and then jump back to the [7] Hybrid pass I get 27ms gpu time and 75 mrays/sec.

I guess, mode 6 sets some states that are not cleaned when using mode 7.

**Comment by wallisc** [comment]
Thanks for filing this! I've resolved the issue, there was indeed silly state leakage that would cause the reflection pass to recursively trace shadow rays (rather than just using the shadow map). I've resolved this in 5a4802b4ba1a765d2a098a9505c49b7ac0944c77 in the develop-dxr branch, it should get merged into master soon
