### ISSUE TITLE
develop-dxr - image quality/traversal bug on AMD Polaris

### ISSUE THREAD

**Issue by Woking-34** [Microsoft/DirectX-Graphics-Samples#332]
Hi,

I have a predefined viewpoint in the Sponza scene. It seems there is a bug in the ray traversal engine using AMD GPUs. With NVIDIA cards there is no such issue/blockiness on the rendered image. Please see the attached images. Thanks!

**Branch:** develop-dxr
**Commit ID:** c18fe2c2baf0e284494dc3b6b618a40907d6cf1f

First two images from AMD, last two images NVIDIA.
 
![polaris_mode6](https://user-images.githubusercontent.com/17589258/39267278-a893d94a-48cc-11e8-9cdb-67a07ecd9f13.png)
![polaris_mode7](https://user-images.githubusercontent.com/17589258/39267279-a8b16726-48cc-11e8-959f-39df9486c439.png)
![gtx1060_mode6](https://user-images.githubusercontent.com/17589258/39267283-a9f2ddd6-48cc-11e8-8851-5129fd1aca97.png)
![gtx1060_mode7](https://user-images.githubusercontent.com/17589258/39267284-aa0f6c1c-48cc-11e8-8b6e-30c6cc371af8.png)

**Comment by wallisc** [comment]
Apologies for the delay, I have a repro and am taking a look. Thanks for the clear A/B image comparisons!

**Comment by wallisc** [comment]
This was a bug where the handling for descriptor tables in local root signatures where textures from the descriptor heap weren't read from weren't properly tagged as non-uniform, and so an incorrect optimization was taking place where the whole wave was using the texture read from the first lane. 

The fix is in dxcompiler, I've just updated the binaries here https://github.com/Microsoft/DirectX-Graphics-Samples/releases/tag/v1.1-dxr, you can use it right away if you're on the develop-dxr branch, otherwise it should be in master soon.
