### ISSUE TITLE
MiniEngine crash on the Nvidia Optimus platform

### ISSUE THREAD

**Issue by lijipeng787** [Microsoft/DirectX-Graphics-Samples#39]
Hi
Function failed when D3D12CreateDevice(...) method take NULL as it first parameter,after  D3D12CreateDevice(...) method finished i found that output pointer (ID3D12Device device) still NULL,
It seems like that device initialization works incorrectly on the multi gpu platforms.
Explicit enumerate available gpu and take them as first parameter sequentially to initialize device with D3D12CreateDevice(...) works correctly on my laptop.

ps: It can enumerate three device(intel hd 4000,nv gt645m,and microsoft base renderer) on my laptop,and every device can accomplish it works.

Graphics card version: gt645m 
Nvidia driver version:353.62
sdk version: 10.0.10240.0 with IDE :vs 2015
Is Driver problems? Or i missed some command line / options that can change device?

In GraphicsCore.cpp:

![image](https://cloud.githubusercontent.com/assets/6110094/10537907/8341582e-7427-11e5-934f-5fbe06684266.png)

**Comment by bobbrow** [comment]
The problem is that DX12 will pick the primary display adapter (the Intel HD 4000) when you pass in nullptr to D3D12CreateDevice, but that adapter doesn't support DX12.

So you either need to do EnumAdapters and test the adapters for DX12 support (as you have done here), or go to the NVidia control panel and specify that you always want MiniEngine to run with the NVidia GPU - which will "hide" the Intel adapter.

I'll need to talk to James and have him update MiniEngine to use EnumAdapters.  We did that for the other samples, but this one hasn't been updated yet.

**Comment by lijipeng787** [comment]
Thanks

**Comment by lijipeng787** [comment]
Thanks your explanation :)
I have been reviewed  relating issue about multi-gpu platform.
