### ISSUE TITLE
Request: ASSIMP integration

### ISSUE THREAD

**Issue by TheeCrowe** [Microsoft/DirectX-Graphics-Samples#42]
This weekend I plan to try and incorporate the Assimp library into one of my test projects that is also using the mini-engine.  I noticed that there is already a stub in the code for loading from ASSIMP library, was this code actually created? if so, are there any plans to release it?

Thank you for all the time you all have put into this, it has really helped!!!

**Comment by bobbrow** [comment]
We're investigating the legal implications of including ASSIMP code in our project.  I'm not sure how long the review will take.

**Comment by TheeCrowe** [comment]
Cool, thanks for the response.

**Comment by sherief** [comment]
Have you tried talking to the ASSIMP team about this?...

**Comment by stanard** [comment]
Hi, I wanted to say where we are with this.  Due to a slightly different OSS license, we won't be directly including the source code or binary for ASSIMP.  However, we have used it internally, and we have projects that depend on it for loading and converting models of various formats.  We will share these projects and include a note for where to download and link with ASSIMP.  We should also provide instructions for how to use these apps.  In the future, we might reconsider including at least the binaries for ASSIMP, but we'll need to speak to the ASSIMP team and our legal team again.

**Comment by amomer** [comment]
Any idea when you may release the sample projects that are using ASSIMP library for loading and converting models of various formats.   
Thank you for all the time you all have put into mini-engine project.

**Comment by stanard** [comment]
I am really hoping to push out a new release soon.  The model loading/converting sample project is ready to go, but I'm in the middle of a major new feature (asynchronous compute) that I'd like to refine a bit more before release.  I don't have a date I can commit to yet.  Thank you for being patient.

**Comment by bobbrow** [comment]
committed to develop branch
