### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by krupitskas** [microsoft/DirectX-Graphics-Samples#446]
Hey!
Currently I'm using miniengine very actively and now I just copypasted Core and Model projects to my solution. It's disabling opportunity to update to last version via git, only with replacing Core library by hand. I think that is good design to have Engine as a 3rd party via some packet manager. 
In non visual studio, everyone mostly using cmake and git submodules. But in VS we have nuget, which we can use. I can add it as a nuget package and as a opensource project, I think we can add appveyour with autobuild and autopublishing.

**Comment by stanard** [comment]
Hi,

MiniEngine is currently on the back burner.  I have made a lot of local improvements like adding glTF 2.0 model, animation, and PBR support, but I have yet to push them to GitHub.  It will take a while to merge.  I also intend to break up Core into multiple components so that if you don't need all the post processing libraries, you don't have to compile all of those shaders.  I recommend holding off on the idea of making a NuGet package for now.  In the mean time, you can quickly create an empty new project using the batch files in the root folder.

Thanks,
James

**Comment by cloudhan** [comment]
@stanard Any progress on the update?

**Comment by jonny2027** [comment]
@stanard I would also like to know of any progress on this.

**Comment by stanard** [comment]
Perhaps I'll push it to an alternate branch so you can try it without breaking anybody dependent on the current version (like the DXR sample.)  I'll look into doing it shortly.

**Comment by stanard** [comment]
I'm preparing to push a new branch. I am just running some tests now. You should still consider it a bit of a "beta" release.

**Comment by stanard** [comment]
I just re-read the original comments and realized that you weren't looking for glTF support at all.  I'm sorry, but I have no plans to develop MiniEngine into a NuGet package at this time.  On the bright side, glTF 2.0 support and physically based shading are now in preview form in the "glTF2" branch.

**Comment by oneengineer** [comment]
Hi ModelConverter_VS15 in ModelConverter Project also has similar problem. Could you also fix the "zlib missing" issue? Also I saw you have included assimp lib through NuGet, however in the readme you asked users to include it by themselves. Perhaps it is OK to include headers and .lib using files provided by NuGet?
