### ISSUE TITLE
Can't run D3D12RaytracingHelloWorld.exe

### ISSUE THREAD

**Issue by JCEG87** [microsoft/DirectX-Graphics-Samples#482]
Hi,

Every time I try to run this project, I get the following error:

---------------------------
D3D12RaytracingHelloWorld.exe - Entry Point Not Found
---------------------------
The procedure entry point DXGIDeclareAdapterRemovalSupport could not be located in the dynamic link library C:\Users\jon.cain\Downloads\DirectX-Graphics-Samples-master\DirectX-Graphics-Samples-master\Samples\Desktop\D3D12Raytracing\src\D3D12RaytracingHelloWorld\bin\x64\Debug\D3D12RaytracingHelloWorld.exe. 
---------------------------
OK   
---------------------------

I can see the entry point is missing in the project settings too, not sure what I'm missing here. Any help would be great. Thanks.

**Comment by pkristof** [comment]
Hi,

That means the OS that you're running the sample on doesn't support the DXGIDeclareAdapterRemovalSupport API. That would be 16299 (Fall Creators 2017 update) or older. What OS are you running the sample on?

We'll address for the API not to get called on older OSes since the sample says 16299 or higher is supported.. You can comment out the call in DeviceResources.h in the meantime.

**Comment by JCEG87** [comment]
Hi,

I'm on 16299.665, version 1709 at work. I tried it last night at home and I believe I'm on a more recent OS but will have to double check when I get home tonight.

I will comment out the call in DeviceResources.h for now, thank you.

**Comment by walbourn** [comment]
The ``DXGIDeclareAdapterRemovalSupport`` entry-point was added in Windows 10 (Version 1803, build 17134)
