### ISSUE TITLE
Question about multithreading shader

### ISSUE THREAD

**Issue by greatelk** [Microsoft/DirectX-Graphics-Samples#49]
Hello,

this is a short question about the shader attached in multithreading sample:

in CalcUnshadowedAmountPCF2x2 function (line 104 of shaders.hlsl)

the following lines:

	// Find sub-pixel weights
	float2 vShadowMapDims = float2(1280.0f / 2, 720.0f / 2); // need to keep in sync with .cpp file
	float4 vSubPixelCoords = float4(1.0f, 1.0f, 1.0f, 1.0f);
	vSubPixelCoords.xy = frac(vShadowMapDims * vShadowTexCoord);
	vSubPixelCoords.zw = 1.0f - vSubPixelCoords.xy;
	float4 vBilinearWeights = vSubPixelCoords.zxzx * vSubPixelCoords.wwyy;

doesn't do anything to the result or i'm missing something?

the return code is:

	return (txShadow.Sample(sampleClamp, vShadowTexCoord).r >= vLightSpaceDepth) ? 1.0 : 0.0f;

the shadow map sampler is using
D3D12_FILTER_MIN_MAG_MIP_POINT

it looks like hard shadows and not percentage close filtering or i'm wrong? 

thanks

Marc

**Comment by bobbrow** [comment]
Good eye.  Yes, you are correct.  There was a D3D11 version of this sample and I believe whoever did the port chose this sample because it was using deferred contexts which are similar to the multithreaded command list recording we allow in D3D12, not because it was rendering shadows.  It looks like some of the PCF code was removed from the pixel shader during the port for some reason.  Fortunately, it looks like the shader compiler doesn't include this dead code in the resulting blob.  I'll get it removed.

**Comment by greatelk** [comment]
ok thanks! these samples are really good :+1:

**Comment by bobbrow** [comment]
I decided to fix the shader and add the 2x2 PCF back in.  The shadows look better now.
