### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by nexelen** [Microsoft/DirectX-Graphics-Samples#5]
When i start debug application thrown exception
![122](https://cloud.githubusercontent.com/assets/2895753/9025607/67898494-391c-11e5-8a61-a1eb9b628e1c.png)
My system:
Windows 10 Pro Insider Preview 10162
Visual Studio 2015
Windows SDK 10240
Videocard: nVidia GeForce GT 630 (353.62 driver version)

**Comment by alessiot89** [comment]
Is that nVidia GeForce GT 630 the Fermi or the Kepler version (there are both GPUs with that name)? I guess it's a Fermi GPU: currently there are no Fermi WDDM 2.0 drivers available, so no Direct3D 12 for you know.

Moreover I suggest you to upgrade to the RTM or at least to the Insider build 10240.

**Comment by bobbrow** [comment]
@nexelen, can you hover over the *hr* variable and tell us what the tooltip says and/or show us the callstack?  That will help us determine whether your card supports DX12 really quickly.  If it doesn't, you can go to the project properties and add **/warp** to the command line to instruct the sample to use the WARP driver instead of the hardware driver.

**Comment by nexelen** [comment]
@bobbrow thank you. Yes my cards most likely dont support DX12 (in hr dosent support in this system). But that start with /warp.
