### ISSUE TITLE
D3DX12.h has a bunch of undefined identifiers

### ISSUE THREAD

**Issue by KingObsidianFang** [Microsoft/DirectX-Graphics-Samples#503]
The title really says it all.  I can't use D3DX12.h because there are a bunch of unindentified identifiers that prevent the solution from building.  I am brand new to D12 (and graphics programming in general) and I was following a tutorial until D3DX12.h broke.  It's also my first time reporting an issue, if there is something else I should have included, please let me know.

**Comment by pkristof** [comment]
Hello,

That is most likely because you're building against an incompatible/older SDK set for your project. The d3dx12.h in master requires the SDK for the current OS release, that is 17763. If updating your SDK+OS to 17763 is not an option, you can download previous releases from the Master branch https://github.com/Microsoft/DirectX-Graphics-Samples/releases.

Best,
Peter

**Comment by walbourn** [comment]
Note that I have a slightly [modified version](https://github.com/walbourn/directx-vs-templates/blob/master/d3d12game_uwp/d3dx12.h) of ``D3DX12.H`` in my [directx-vs-templates](https://github.com/walbourn/directx-vs-templates) that matches the current version from this repo, but uses conditional compilation so it works back to Windows 10 SDK (14393) since I support VS 2015 as well as VS 2017.

That said, you should move to the latest toolset and SDK when you can...
