### ISSUE TITLE
Isn't GroupMemoryBarrierWithGroupSync needed between groupshared reads and writes?

### ISSUE THREAD

**Issue by shenchi** [Microsoft/DirectX-Graphics-Samples#517]
Hope I'm not asking a stupid question here. I'm reading UpsampleAndBlurCS.hlsl and see that there is no sync between loads and stores in BlurHorizontally() or BlurVertically(). If I understood correctly, the indices for reads and writes are overlapping across the threads here. Isn't it possible that one thread would read the value wrote by another thread?

I'm thinking about lock-step execution within a wavefront on GCN, as the group size here is (8, 8, 1) = 64 threads, but this won't apply for other GPUs, right? I also tried to look at the assemblies generated for GCN, it looks like the compiler inserted s_waitcnt or s_barrier(if the group size is larger than 64) accordingly regardless of the usage of GroupMemoryBarrierWithGroupSync(), and again, I don't think all other compilers would guarantee this. 

I don't know if I'm on the right track. Could anyone elaborate me what's going on here? I'd really appreciate it :)

Thanks,
Chi

**Comment by stanard** [comment]
BlurHorizontally() uses four threads per row to generate two blurred pixels each.  I think on all GPU architectures these operations happen in unison because they are less than--and a perfect divisor of--the natural SIMD width (16 on GCN).  What this means is that all threads load values into registers, convolve them, and write them out simultaneously.  So there isn't a data hazard.  BlurVertically() doesn't have a data hazard either, but that's primarily because it writes to memory rather than LDS, so no values are overwritten.

This code has definitely been tested on Nvidia, AMD, and Intel.  I haven't heard of other architectures having a problem either.

**Comment by shenchi** [comment]
Thank you James! It's really helpful!
