### ISSUE TITLE
Multiple window problems

### ISSUE THREAD

**Issue by Hlexyn** [Microsoft/DirectX-Graphics-Samples#52]
Sorry to bother, but I have been having trouble with multiple windows. I put each window into its own thread to aid with debugging and regardless of whether they share a command queue, or have their own, the window threads always seem to hang at one of these 3 lines:

`m_d3dCommandQueue->ExecuteCommandLists(_countof(ppCommandLists), ppCommandLists);`

`>	Test.exe!Microsoft::WRL::ComPtr<ID3D12CommandQueue>::InternalRelease() Line 196	C++ (called from 	ThrowIfFailed(m_swapChain->Present(1, 0));)`

`m_swapChain->ResizeBuffers(FrameCount, 0, 0, DXGI_FORMAT_R8G8B8A8_UNORM, 0);`

One window works perfectly but uploaded the code just in-case I've done something stupid.
[http://pastebin.com/wALUNaz4](http://pastebin.com/wALUNaz4)

Any help you can give would be greatly appreciated. Thank you.

**Comment by Hlexyn** [comment]
Never mind, had an epiphany on the lavatory. Wrapped everything with a recursive mutex and it's all fixed. It didn't occur to me that the central object to aid in multi-threaded rendering wouldn't be thread safe. Again, sorry to bother.

**Comment by Seniltai** [comment]
Hlexyn, this is the same issue i'm having. I've also compared this issue in DX11, where it does work without mutexes (having a mutex in there defeats the purpose of multithreading in the first place, since it can also deadlock in Present). Think this is still worth something to fix or sidestep in a more desirable way, otherwise people making editors with DX12 are going to have a bad time..

**Comment by anyeung** [comment]
Hi guys, just wanted to let you know that we're aware of this issue and will be try to get fixes for it in for the next OS release.

**Comment by Seniltai** [comment]
Awesome, thanks!
