### ISSUE TITLE
how to generate solution for SSAO in visual studio?

### ISSUE THREAD

**Issue by mishradiwakar09** [microsoft/DirectX-Graphics-Samples#530]
i want to see the result for SSAO how do we generate solution(.sln) for in visual studio i have tried copying the ssao.cpp and adding all library but getting loads of error are there any method from where we can generate .sln file like CMake generate for Opengl?
please guide

**Comment by stanard** [comment]
There is a Python script and batch file for generating new projects (app or lib).  See MiniEngine/CreateNewSolution.bat.  But SSAO is pretty tightly integrated with other Core effects.  I've planned to break out all post processing effects into their own library so that Core compiles faster but haven't done it yet.  If you just want to see the effect of SSAO, you can enter the debug tweaks menu and disable other effects or turn on the debug view of SSAO (which shows just grey scale occlusion.)
