### ISSUE TITLE
Root Signature 1.1 errors

### ISSUE THREAD

**Issue by simco50** [Microsoft/DirectX-Graphics-Samples#535]
I've modified the RootSignature code to use version 1.1 to make use of the ability to specify a descriptor to be static. (In `RootSignature.cpp / RootSignature::Finalize()`)
However after doing that, I'm seeing validation errors like these:
`D3D12 ERROR: ID3D12CommandQueue::ExecuteCommandLists: Descriptor (at CPU Handle 0x0000000000005F45) is bound as STATIC (not-DESCRIPTORS_VOLATILE) on Command List 0x00000158FF187F30:'CommandList'. It was changed by CopyDescriptors call, but it is invalid to change it until the command list has finished executing for the last time. [ EXECUTION ERROR #1001: STATIC_DESCRIPTOR_INVALID_DESCRIPTOR_CHANGE]`
I've been reading some more about RS 1.1 and I still don't understand why I'm getting these errors. The descriptors definitely don't get modified during flight.
To double check that, I've force idled the CPU/GPU to only execute one frame at a time and I still get the errors.
Making the descriptors volatile fixes it but I don't understand why that is necessary because the descriptors don't change during execution.
Is there anything I'm missing?
Thanks!

**Comment by billkris-ms** [comment]
Hello,

Thank you for your feedback.  

This is not necessarily about modifying a descriptor in flight.  Static descriptors must not be modified at all after setting the descriptor in the command list recording.  This allows for driver optimizations (such as constant-folding) during the rest of the command list recording.  From this error, it appears that you recorded a Set[Graphics|Compute]RootDescriptorTable operation referencing a static descriptor that was modified by a CopyDescriptors call prior to ID3D12CommandQueue::ExecuteCommandLists.

Since this site is intended for reporting issues on the DirectX-Graphics-Samples repo, your question may be answered more quickly (and accurately) on http://forums.directxtech.com.  Also, any answers you do receive are more likely to benefit other developers with the same question.

Thanks,
-Bill

**Comment by simco50** [comment]
Hi,
Thanks for the reply.
After rereading the documentation with this in mind, it's making more sense now.

It says:
` Static descriptors mean the descriptors in a descriptor heap pointed to by a root descriptor table have been initialised by the time the descriptor table is set on a command list / bundle (during recording), and the descriptors cannot be changed until the command list / bundle has finished executing for the last time.`

From this I understand you can't overwrite a descriptor on a command list until it has been submitted and finished for the last time and more importantly, you can't overwrite a descriptor even before submission.
This cleared things up, thanks.
