### ISSUE TITLE
Ray traced 'holes' appearing on procedural geometry edges

### ISSUE THREAD

**Issue by digbeta** [microsoft/DirectX-Graphics-Samples#550]
I have been working with the Ray Tracing procedural geometry example and recently found an issue I am unable to diagnose.  I have created a new procedural shape: (sdTorus(p, h) + 0.045*sin(20.0*p.x)*sin(20.0*p.y)*sin(20.0*p.z)).  This gives the shape below:

![shape-holes](https://user-images.githubusercontent.com/17113489/60047173-e9da7f80-967d-11e9-92d7-f36531368a2d.png)

I was evaluating the resolution independence of images produced using this method and when viewing the shape very closely I found that often times you can see transparent holes in the geometry that I can't explain.   I'm not certain, but these holes seem more prominent when the shape surface is concave.  See the marked bounding boxes in the images below showing how the rays are tracing through geometry and don't seem to be rendering a hit.

![holes1](https://user-images.githubusercontent.com/17113489/60047799-70dc2780-967f-11e9-88bb-14fab9873b29.png)

Note in the picture above and below you can see the green of the object behind the yellow shape along with either the ground or background.

![hole2](https://user-images.githubusercontent.com/17113489/60047803-746fae80-967f-11e9-82e2-3c34c725d10d.png)

![holes4](https://user-images.githubusercontent.com/17113489/60047808-789bcc00-967f-11e9-8593-c0381e3a00e6.png)

I thought maybe this was noise related, but this only seems to be happening on edges.  Also, I think this is also present on the demo shapes, see the images below.  First image is a perspective through the intersected round cube:

![squarehole](https://user-images.githubusercontent.com/17113489/60048696-8baf9b80-9681-11e9-8126-00a0e463dc50.PNG)

and the gear shape (see below):

![gear](https://user-images.githubusercontent.com/17113489/60047784-691c8300-967f-11e9-88eb-2ed320fc21d0.PNG)

Any help is appreciated.

**Comment by pkristof** [comment]
Hi,
This is likely due to the nature of the SDF sphere tracer (implemented in RaySignedDistancePrimitiveTest(...)). The sphere tracer adjusts its iteration step based on the SDF/distance to a geometry. For rays grazing the surface it can get to close distances, and thus use smaller iteration steps, eventually running out of the allowed number of steps "MaxSteps" before crossing the surface boundary and, thus, returning a NoHit result for the objects AABB. You can increase stepScale variable defined per object for object this impacts. The variable scales the ray marching steps taken. You can also try increasing "threshold" (in RaySignedDistancePrimitiveTest()) to accept surface hits sooner, at the cost of more false positives.

**Comment by digbeta** [comment]
Peter,

Thanks so much for your quick reply.  I can confirm your suggested fix works.  I wasn't as familiar with that portion of the example code, so thanks for pointing that out.

Thank you again!

-Eric
