### ISSUE TITLE
D3D12HDR: "Current Output HDR Support" is false

### ISSUE THREAD

**Issue by Ocrosoft** [microsoft/DirectX-Graphics-Samples#553]
Device: Lenovo ThinkPad X1 Extreme
Graphics Card1: Intel UHD Graphics 630
Graphics Card2: NVIDIA GeForce GTX 1050 Ti Max-Q 4GB GDDR5
"Settings"-"Apps"-"Video playback"-"Stream HDR video" : ON

Using "Movies & TV" to play a HDR10 video, it looks good. But run D3D12HDR sample, the  "Current Output HDR Support" is false, it means that the screen isn't support HDR?
I think the result may be wrong: When use 10bit format, press "H" to switch the output signal to "ST.2084", the display is same as before.

**Comment by kpsam2000** [comment]
Display need to support HDR10 & you need to enable the same in OS page.

**Comment by Ocrosoft** [comment]
> Display need to support HDR10 & you need to enable the same in OS page.

Thanks, after enabled the "HDR and WCG" option, HDR Support is true. Besides, if I disable "HDR and WCG" option, there are any way to detect HDR support?(In other words, how to check if windows has "HDR and WCG" option?)

**Comment by kpsam2000** [comment]
Try https://docs.microsoft.com/en-us/uwp/api/windows.graphics.display.advancedcolorinfo.isadvancedcolorkindavailable#Windows_Graphics_Display_AdvancedColorInfo_IsAdvancedColorKindAvailable_Windows_Graphics_Display_AdvancedColorKind_

**Comment by jgavert** [comment]
Found this by pure chance.
And I could be wrong, but here goes.

The HDR, the lenovo displays have, are somehow connected to Dolby Vision as that's the software they suggested downloading for my laptop when they finally got it working.

What this means is that the display doesn't support HDR10, which is what the windows supports to my understanding.

My laptop is Lenovo Thinkpad X1 gen3 with "HDR display".

To my understanding, Dolby vision is only available through Dolby's own api's and that's not the same as Windows HDR. And that's why there is a notion that it's only "HDR Video" not the usual what actual HDR 10bit displays have. It's more of HDR for netflix and apps like that.

To get the right HDR enabled, do as follows:
When you open "Display settings", there should be text saying "Play HDR Games and apps" and a switch under it to toggle HDR on or off.
If you don't have option named like that in the settings, you won't be able to get the D3D12HDR example to detect or display HDR.
That's it.
Hope that helps, and yes, I was sort of disappointed that the HDR my laptop supported was Dolby Vision also.

**Comment by Ocrosoft** [comment]
@jgavert 
Thanks, you are right. Thinkpad X1 Extreme is only support Dolby Vision, not HDR10, when I play a HDR10 video, the "Movies & TV" will change HDR content to SDR, then display it. After I connected X1 to a display which support HDR10, Windows' display settings will appear an option, and I can enable the HDR support.
