### ISSUE TITLE
The triangle move but shake in D3D12HelloConstBuffers.

### ISSUE THREAD

**Issue by zengdc99** [microsoft/DirectX-Graphics-Samples#554]
I run the sample D3D12HelloConstBuffers. I can see a triangle move from left to right.
But the triangle shake randomly.
I tried on two computer with GTX960 and GTX 1650, get the same issue.

**Comment by kokole** [comment]
Same issue.

**Comment by kokole** [comment]
It seems to be a bug in the debug layer? I built it with release and now the stutter is gone.
With it enabled it somehow doesn't present some frames.

**Comment by walbourn** [comment]
You should see if you have uninitialized variables. You can enable the debug layer in your release build to see if that's really related or not.

**Comment by kokole** [comment]
If I turn the debug layer on I see lots of INFO Create/Destroy ID3D12GraphicsCommandList and the sample stutters a lot in Release. With debug layer off those messages are gone and there is no stutter.

**Comment by walbourn** [comment]
OK, then it's not a bug. It's what happens when you have lots of debug output from any program. There are mechanisms for suppressing specific messages or whole categories of messages from the debug layer.

Which INFO messages are you getting in particular?

**Comment by kokole** [comment]
`[8020] D3D12 INFO: Create ID3D12GraphicsCommandList: Addr=0x000002446BE26780, ExtRef=1, IntRef=0 [ STATE_CREATION INFO #560: CREATE_COMMANDLIST12]
[8020] D3D12 INFO: Destroy ID3D12GraphicsCommandList: Name="unnamed", Addr=0x000002446BCAF3A0 [ STATE_CREATION INFO #586: DESTROY_COMMANDLIST12]
[8020] D3D12 INFO: Create ID3D12GraphicsCommandList: Addr=0x000002446BCAF3A0, ExtRef=1, IntRef=0 [ STATE_CREATION INFO #560: CREATE_COMMANDLIST12]
[8020] D3D12 INFO: Destroy ID3D12GraphicsCommandList: Name="unnamed", Addr=0x000002446BE26780 [ STATE_CREATION INFO #586: DESTROY_COMMANDLIST12]`

Like that, repeated (I'm guessing every frame). And I realized that of course those messages won't show up if I have the debug layer off, because it's off...
What's weird is that I'm getting stutter from this Microsoft's own graphics sample.
If I use some 3rd party FPS counter overlay, it disappears the same frames that the triangle stutters.
Not sure if it's a driver issue or what. I have a GTX 1070 with latest drivers.

**Comment by walbourn** [comment]
It's unusual to create/destroy command-lists every frame (i.e. it's a heavy-weight operation), hence why it's an INFO message. You should create them once, and then reuse them in general.

In fact, if I build & run the latest version of D3D12HelloConstBuffers using Windows 10 (17763), I don't see any INFO messages in that sample at all... I'll upgrade to 18362 and see if it repros.

**Comment by kokole** [comment]
Yes, I'm on 18362

**Comment by jenatali** [comment]
Two things:
1. The INFO messages for creates and destroys are due to the debug layer virtualization of command queues. See [ID3D12Debug1::SetEnableSynchronizedCommandQueueValidation](https://docs.microsoft.com/en-us/windows/win32/api/d3d12sdklayers/nf-d3d12sdklayers-id3d12debug1-setenablesynchronizedcommandqueuevalidation).
2. INFO messages are disabled by default. You'd need to either explicitly enable them from ID3D12InfoQueue's filter APIs, or by using the DirectX Control Panel.

**Comment by walbourn** [comment]
```
#ifndef NDEBUG
    // Configure debug device (if active).
    ComPtr<ID3D12InfoQueue> d3dInfoQueue;
    if (SUCCEEDED(m_d3dDevice.As(&d3dInfoQueue)))
    {
#ifdef _DEBUG
        d3dInfoQueue->SetBreakOnSeverity(D3D12_MESSAGE_SEVERITY_CORRUPTION, true);
        d3dInfoQueue->SetBreakOnSeverity(D3D12_MESSAGE_SEVERITY_ERROR, true);
#endif
        D3D12_MESSAGE_ID hide[] =
        {
            D3D12_MESSAGE_ID_CREATE_COMMANDLIST12,
            D3D12_MESSAGE_ID_DESTROY_COMMANDLIST12,
        };
        D3D12_INFO_QUEUE_FILTER filter = {};
        filter.DenyList.NumIDs = _countof(hide);
        filter.DenyList.pIDList = hide;
        d3dInfoQueue->AddStorageFilterEntries(&filter);
    }
#endif
```

**Comment by zengdc99** [comment]
The release is Ok. The issue only happen in debug.
