### ISSUE TITLE
Compatibility of D3D12on7 with Windows 8/8.1

### ISSUE THREAD

**Issue by Redundanz** [microsoft/DirectX-Graphics-Samples#569]
This should generally work without issue, correct?

**Comment by jenatali** [comment]
No, D3D12on7 only works on Windows 7.

**Comment by walbourn** [comment]
Note that if you look at the OS usage rates on the [Valve Steam Hardware Survey](https://store.steampowered.com/hwsurvey), you'll see it's 71% Windows 10 (x64), 20% Windows 7 (x64). Windows 8.x is less than 3%.

D3D12on7 also only supports Windows 7 SP1 (x64) because Windows 7 (x86) usage on Steam is 1%.

**Comment by Redundanz** [comment]
i see.
i was of the impression that compared to windows 7 there was nothing "missing" in windows 8 that would stop it from working, meaning supporting it for windows 7 would entail windows 8 support because of no additional effort...

thanks for clarifying.

**Comment by mirh** [comment]
Not even if you installed Win7 drivers on 8?
I always imagined every windows to be more or less a strict superset of the previous one.
