### ISSUE TITLE
D3D12HeterogeneousMultiadapter not working

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#57]
Hi,
I have the D3D12HeterogeneousMultiadapter sample always fail on 
D3D12CreateDevice(ppAdapters[i], D3D_FEATURE_LEVEL_11_0, IID_PPV_ARGS(&m_devices[i])), 
no meaningful message. The machine I ran into this has dual Nvidia 680m (but the sample fail even on creating device from the first adapter)  with drive version 358.91(the latest driver I can get up to today). The same issue occurred with both SLI enabled and disabled.  

One thing need noting is that when I run dxcap -info I got 

Feature Support       : No
D3D9 Driver Support   : Fail
D3D10+ Driver Support : Fail
OS Version Check      : Pass
Driver Version Check  : Fail      

for SLI disabled, but

Feature Support       : No
D3D9 Driver Support   : Pass
D3D10+ Driver Support : Pass
OS Version Check      : Pass
Driver Version Check  : Fail

for SLI enabled.

**Comment by bobbrow** [comment]
Which adapter is failing to create the device?  Do the single adapter samples work for you?  I'm not sure whether you have an Intel GPU in this laptop as well and whether you are disabling that for running the samples.  You may need to modify the GetHardwareAdapters method to get the DXGI_ADAPTER_DESC1 of each of the adapters that you're trying to create devices for so that you can see which adapters the sample is trying to use.

**Comment by pengliu916** [comment]
I will give it a try when I back home, but now I am in my lab and I have a laptop which has one Nvidia 980M. The sample now can run, but I just see a black screen with one red line in the middle. But when I switch the adapters in the code (swap the 0, 1 in code line 78,79, I see triangles.... So seems something is weird here too....

**Comment by pengliu916** [comment]
I updated my driver to today's latest one, now the error changes to 
HRESULT openSharedHandleResult = m_devices[Secondary]->OpenSharedHandle(heapHandle, IID_PPV_ARGS(&m_crossAdapterResources[Secondary][n]));
No clue what causes the fail, the validation layer only says
D3D12 WARNING: ID3D12Device::RemoveDevice: Device removal has been triggered for the following reason (DXGI_ERROR_DRIVER_INTERNAL_ERROR: There is strong evidence that the driver has performed an undefined operation; but it may be because the application performed an illegal or undefined operation to begin with.). [ EXECUTION WARNING #233: DEVICE_REMOVAL_PROCESS_POSSIBLY_AT_FAULT]

**Comment by bobbrow** [comment]
Did you update both the NVidia and the Intel drivers?  Since it sounds like you are using a laptop, I'm assuming that your 980M is the Primary (draws the triangles) and the Intel is the secondary (does the blur).  You'll need to set a breakpoint in the GetHardwareAdapters method like I mentioned in my earlier message.  If you're still having trouble, please send me the driver version you're using for both GPUs and I'll see if I can find a laptop with a similar spec here.

**Comment by pengliu916** [comment]
So here the laptop I use have i7-4980HQ(Iris Pro 5200 as GPU) gpu driver version is 10.18.15.4256 with nvidia 980m with version 359.00.

As normal laptop there is a physical bottom to switch using Iris5200 or nvidia 980m. So when I use Iris5200, the sample can run. But when I switch to nvidia 980m, the thing I mentioned in my previous post happend (and when I switch to nvidia 980m, nvidia 980m is the Second. The Primary is displayed as 'Microsoft Basic Render Driver') 

The drivers are all up-to-date.
So I am really confuse about that, and I don't have desktop machine like this to test on

**Comment by bobbrow** [comment]
Issue #16 has a link to a newer Intel driver, though it sounds like that's not your problem...  So you can only have one GPU active at a time?  Or are both GPUs active when you set the switch to Iris5200?

Also, just double checking since it looks like only one GPU is active at a time...  Do you have the "Graphics Tools" optional feature installed as described in the readme.md file?  The Microsoft Basic Render Driver that ships with Windows 10 does not support DirectX12, so I would understand why D3D12CreateDevice fails for you in that case.

For the 680M laptop, it is possible that the driver is linking the two GPUs into a single device (perhaps even with SLI off), and reporting that the D3D device has 2 "nodes."  If this is the case, then you have "homogeneous" multiadapter and the sample will try to use Microsoft Basic Render Driver for the other GPU.  You'll need to look at GetHardwareAdapters to see if that is the case.  Again, you will need the "Graphics Tools" optional feature if that is what is going on.
