### ISSUE TITLE
Why commandlist reuse seems not been encouraged

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#58]
It seems lots of samples have the following iteration pattern every frame:
commandallocator.reset() -> commandlist.reset() -> buildcommandlist -> commandlist.close().....
even though there are only 3-5 different commands sequence(depend on the backbuffer count). but most samples will recreate the whole commandlist every frame instead of create these commandlist a head of time and reuse them every frame.

So I have modified the D3D12HelloConstBuffers code, I create 3 (backbuffer count) commandlist objects from one allocator, and build 3 different command lists for them, and the difference is only the OMSetRenderTargets function where 3 commandlist use different backbuffer. Then in OnRender function, I get rid of the allocator reset, commandlist build.... and just execute the right commandlist based on current backbuffer index.  And it turned out it works as expected.

So my question here is why this pattern is not encouraged(or maybe I am wrong?), it seems by doing so we can save lots of cpu cycles

**Comment by bobbrow** [comment]
What you are doing is totally valid, though it is hard to fully answer this question because "it depends on the scenario."  If you have unchanging command list content, then you certainly can cache command lists and re-execute them at the appropriate times.  You might also consider using Bundles as well since those are meant to improve performance even further when you have more than just a few draw calls in them.  In either case, you will need to profile your app and ensure that you are getting the performance you want from the technique that you choose.

But to more specifically answer your question about the samples, I had a brief discussion about this with a few of my colleagues here are Microsoft before we launched the samples and we decided that since most real games are going to have different command list contents throughout their lifetimes, that we would not write the samples in a way that was tailored to the specific static scenarios that they target (i.e. caching the command lists).

If your game so happens to have unchanging command list contents across long stretches of time, then you are certainly encouraged to make optimizations such as this for your game.  The trouble with SDK samples is that there is only so much we can show at a time without making the code overly challenging to comprehend and there is only so much time available for us to add more of them.  However, I will take this as feedback and maybe we can update the HelloWorld samples or something since those are meant to be the simplest code possible.  In their current form, the samples are aiming to be as consistent with each other as possible so that you can look at any one of them and quickly feel comfortable with the code.
