### ISSUE TITLE
Fullscreen sample for win32 is bugged on 1280x1024 monitor

### ISSUE THREAD

**Issue by zxcq544** [microsoft/DirectX-Graphics-Samples#631]
Hello. Fullscreen sample has black lines on top and bottom with 1280x1024 monitor. If I change resolution in source from 1280x720 to 1280x1024 then in windowed mode black lines appear on left and right side and when I switch to fullscreen then background is rendered fully but drawn white line is not fullscreen - it acts as if it is drawn 1280x720.
IMO resolutions should not be hard coded in source - instead they should be taken from win 32 api function `EnumDisplaySettings` or from Directx `GetDisplayModeList` because it will fix this bug for all possible aspect ratios, not only 4:3 but also for 21:9 etc.

Screenshots below
1. Not fullscreen window because of hard coded resolutions:
https://pastenow.ru/f51be642c8b72c319dbf664a401b28f4
2. Black lines on top and bottom in fullscreen 1280x1024 because of hard coded resolutions:
https://pastenow.ru/e18fd6bb597fd4c975b5bbc958355043
3. Black lines on right and left side in wondowed with resolution in code changed to 1280x1024:
https://pastenow.ru/63ab9a73f677a8ccc26c5250544e96c3
4. White line not drawn fullscreen in fullscreen mode when resolution changed in source to 1280x1024:
https://pastenow.ru/038766a3cc388077c196e07a6af2b4c8

**Comment by walbourn** [comment]
The fullscreen example is trying to demonstrate how to create a fullscreen experience with a consistent aspect-ratio as many times have assets that do NOT scale arbitrarily. The 'letter-boxing' is therefore intentional.

If you want a 'maximized window' experience, then you should take a look at how the fullscreen experience is implemented in [directx-vs-templates](https://github.com/walbourn/directx-vs-templates/blob/master/d3d12game_win32_dr/Main.cpp) which is also discussed in [this blog post series](https://walbourn.github.io/care-and-feeding-of-modern-swapchains/).
