### ISSUE TITLE
Why using mutex instead of lightweight CRITICAL_SECTION ?

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#64]
Hi 

After looking through miniEngine for awhile, I noticed you guys exclusively using std::mutex to enforce correctness in multi-thread scenarios. IIRC mutex have heavier overhead when compare to CRITICAL_SECTION, so I just wondering what's the specific reason to use mutex in miniEngine?

Thanks

**Comment by stanard** [comment]
std::mutex was chosen over CRITICAL_SECTION because it's more modern and standardized (with C++11, if I recall correctly.)  It results in cleaner code, in my opinion, and its frequency is small due to our current lack of parallelism with command lists.  Once we properly implement and tune parallel command lists, we may implement our own "lightweight mutex" using atomic compare and swap, which is how CRITICAL_SECTION is probably implemented.  Where threads might need to sleep for a long time, a proper system call is the right way to go so that the OS can replace them with unblocked threads.  Long story short, we just haven't gotten around to tuning our multithreaded performance, but it's on our radar as we move to take advantage of DX12's better multithreading capabilities.

Cheers,
James
