### ISSUE TITLE
raytracing D3D12RaytracingRealTimeDenoisedAmbientOcclusion compile error 

### ISSUE THREAD

**Issue by normrubin** [microsoft/DirectX-Graphics-Samples#645]
I'm guessing some kind of version skew - anyone know if the sdk number should different?

C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86\dxc.exe /I"c:\users\norrubin\DirectX-Graphics-Samples\Samples\Desktop\D3D12Raytracing\src\D3D12RaytracingRealTimeDenoisedAmbientOcclusion\\" /IRTAO/shaders /ISampleCore/shaders /ISampleCore/shaders/util /nologo /T cs_6_3 /Fh "obj\x64\Release\\CompiledShaders\GenerateGrassStrawsCS.hlsl.h" /Vn "g_pGenerateGrassStrawsCS" SampleCore\Shaders\util\GenerateGrassStrawsCS.hlsl
FXC : error : validation errors [c:\users\norrubin\DirectX-Graphics-Samples\Samples\Desktop\D3D12Raytracing\src\D3D12RaytracingRealTimeDenoisedAmbientOcclusion\D3D12RaytracingRealTimeDenoisedAmbientOcclusion.vcxproj]

FXC : error : at 'call void @dx.op.rawBufferStore.f32(i32 140, %dx.types.Handle %1, i32 %416, i32 32, float undef, float undef, float undef, float undef, i8 7, i32 4)' in block '#8' of function 'main': uav store write mask must match store value mask, write mask is 7 and store value mask is 0 [c:\users\norrubin\DirectX-Graphics-Samples\Samples\Desktop\D3D12Raytracing\src\D3D12RaytracingRealTimeDenoisedAmbientOcclusion\D3D12RaytracingRealTimeDenoisedAmbientOcclusion.vcxproj]

**Comment by oberth** [comment]
While this may come in late for the OP, a friend asked me to take a look at this issue as he's been hitting the same one. Might as well help others here plus notify whom it may concern at Microsoft. (@stanard seems to be popping up in other issues).

_**Note:** transitioning to `dxc` seems to have borked the generation of folders referenced by the output paths, so either fix the build steps or manually create the folders `Shaders`, `CompiledShaders` and `Models` where the `failed to write` error pops up (and variants there of). Same goes for ensuring SDK build is that of 19041._

You're hitting the DXC validation error `hlsl::ValidationRule::InstrWriteMaskMatchValueForUAVStore` in `GenerateGrassStrawsCS.hlsl`. This particular error is not caught in `Debug` because `dxc` due to disabled optimizations. You're in `Profile/Release` given the lack of `/Zi /Od` (No debug info, disabled optimizations) and the presence of `/Vn`. 

The fix is rather simple, a matter of _declared, but undefined_:

```hlsl
VertexPositionNormalTextureTangent vertex;
vertex.position = 0;
```

needs to be:

```hlsl
VertexPositionNormalTextureTangent vertex;
vertex.position = 0;
vertex.normal = 0;
vertex.textureCoordinate = 0;
vertex.tangent = 0;
```

To remove the validation error under optimization, to compile successfully with `dxc`. 

[Fixed and running on an RTX 3080 (built Release executable).](https://i.imgur.com/XT8MEVI.png) Not really the best denoising (or anywhere close), but neat sample. Have fun.

**Comment by walbourn** [comment]
With the latest DXC.EXE builds in the Windows SDK, this is no longer happening.
