### ISSUE TITLE
Question on PIX, with DirectX 12 ExecuteCommandLists, and submitting multiple command lists

### ISSUE THREAD

**Issue by cpyburn** [microsoft/DirectX-Graphics-Samples#685]
See the PIX image: the two red arrows represent these two command lists that I have tried executing as individual command lists.
m_deviceResources->GetCommandQueue()->ExecuteCommandLists(1, m_deviceResources->BatchSubmit + m_deviceResources->COMMAND_LIST_THREAD2);
m_deviceResources->GetCommandQueue()->ExecuteCommandLists(1, m_deviceResources->BatchSubmit + m_deviceResources->COMMAND_LIST_THREAD3);

As one ExecuteCommandLists but with two command lists
/m_deviceResources->GetCommandQueue()->ExecuteCommandLists(2, m_deviceResources->BatchSubmit + m_deviceResources->COMMAND_LIST_THREAD2);

No matter what, they always execute one after another according to PIX.  I thought submitting multiple command lists and/or multiple ExecuteCommandLists would start parallel tasks on the GPU?

My best guess is that I need multiple command queues but can't find a lot of documentation on this? I want to make sure this is correct before I head down a path of programming something that doesn't work.  

If creating more command queues is the way to do parallel tasks on the GPU, then what is the point in submitting multiple command lists if it just runs them in order of submission?  Is it just so you can record them asyc on the CPU?
![Capture](https://user-images.githubusercontent.com/17934438/104250875-2f16fb80-5434-11eb-9a14-bf3706f658e1.PNG)

**Comment by sebmerry** [comment]
I would recommend our [Discord server](http://discord.gg/directx) for questions like this in the future, the community and MSFT employees are very helpful.

To answer your question, don't try to handle multiple 3D queues. Only one queue is needed per engine type (3D, Compute, Copy) and those engines can run async to each other. Care should be taken to sync work in those queues, see [here](https://docs.microsoft.com/en-us/windows/win32/direct3d12/user-mode-heap-synchronization). Work in a single queue is executed sequentially (it's a queue), but I _think_ you're looking to make sure that a queue's work is pipelined when possible (overlaps). Is that correct? To see this overlap in PIX, look at the "Execution Duration" section (bottom blue lines in your image). That shows you when draws start/end.

In your example, since you're just using the 3D queue, I recommend:
- use 1 command queue (3D)
- submit command lists into a single ExecuteCommandLists() call (work from different ExecuteCommandLists() calls _cannot_ overlap at all because ExecuteCommandLists() does sync).
- minimize/optimize resource barrier usage

That will allow the GPU to overlap as much work as possible on the 3D queue. Please note unnecessary or inefficient resource barriers, etc. will prevent the GPU from overlapping draw calls. For example, "Draw A, Draw B, Barrier" is better than "Draw A, Barrier, Draw B"; in the second example the Barrier will prevent Draw A and Draw B from overlapping (I suspect this is that case in your image above). 

As for command lists, you're right: they allow you to record GPU commands async on the CPU.

**Comment by cpyburn** [comment]
Thank you, from here on out I will use the Discord server.

> For example, "Draw A, Draw B, Barrier" is better than "Draw A, Barrier, Draw B"; in the second example the Barrier will prevent Draw A and Draw B from overlapping (I suspect this is that case in your image above).

See the PIX image, I have no Barriers between the command lists and still they are getting no parallel work on the GPU.  Is it because there is not enough GPU cores to execute the second command list while the first command list is executing?
![Capture1](https://user-images.githubusercontent.com/17934438/104285337-1bda4f00-5479-11eb-8438-b0174e6a5751.PNG)

**Comment by sebmerry** [comment]
@cpyburn Ah I think the issue here is that you're using bundles. The bundles are baked, so that will impact what the drivers can do.  Are you able to try those as regular command lists and see if they overlap?

**Comment by cpyburn** [comment]
@sebmerry so you are right, the bundles seem to be causing the issue.  So now my question is why even have bundles?  I thought using bundles saves write time on the CPU, but now it looks like they destroy the chance of the GPU doing its job with parallel tasks.

**Comment by sebmerry** [comment]
@cpyburn I'm glad to hear that you were able to get better pipelining with direct command lists in your scenario! Did direct command lists provide an overall perf win for you? Bundles do have their uses, but there are always exceptions :). Depending on the hardware, you are saving some CPU cost but giving up some flexibility from the GPU/driver side. In some titles, like Forza, bundles turn out to be an overall win. Typically, if you're trying to squeeze out every last bit of performance, you will have to profile different approaches to find out what works best for your unique scenario/hardware.

**Comment by cpyburn** [comment]
@sebmerry do you think that I am adding something to my bundle that could be causing this behavior?

**Comment by sebmerry** [comment]
@cpyburn perhaps the PIX layout throwing me off, do you have Draw calls _in_ your bundles? Or are they really just setting state?

**Comment by cpyburn** [comment]
@sebmerry I was trying to see what I could get away with in a bundle, but even setting just the pipeline, heap, and root descriptor has the same results.  I am moving on.  I will probably revisit once the project moves further along.
