### ISSUE TITLE
New MiniEngine version does not build

### ISSUE THREAD

**Issue by Zeblote** [microsoft/DirectX-Graphics-Samples#695]
Hi, it seems the new version of MiniEngine no longer builds when following the steps in the readme. It results in this error:

`The build tools for v142 (Platform Toolset = 'v142') cannot be found. To build using the v142 build tools, please install v142 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".`

Except that toolset obviously _is_ installed:
![image](https://user-images.githubusercontent.com/6764788/109373526-989d7d00-78af-11eb-9e78-d56266f5a8ee.png)

And so is the latest windows sdk:
![image](https://user-images.githubusercontent.com/6764788/109373531-a05d2180-78af-11eb-9be0-4da4fc40705d.png)

Trying to fix the toolset version leads to a broken menu with no entries:
![image](https://user-images.githubusercontent.com/6764788/109373539-ad7a1080-78af-11eb-9b8b-fa36f0cd9f04.png)

Using VS 16.8.6 and Windows 10 20H2. What am I missing?
The other samples compile fine with the same setup. Only this one is broken.

**Comment by DrGr4f1x** [comment]
I have exactly the same problem on the latest version.

**Comment by stanard** [comment]
Thanks for bringing this to my attention.  I was unaware that I had introduced a build problem because it builds locally without error. Are you both using a new clone of the repo, or have you made changes to any projects?  I removed the *_VS15 and *_VS16 variations and consolidated on one configuration which requires VS16 (2019) and 19041 SDK (20H2). VS2019 comes with v142 as the default toolset.  In the past, I've seen that error message when building a VS2019 project with VS2017 (when the minimum required version is only VS2017.)  I can't work on this today, but I'd love to get it patched up by the weekend.  If either of you come up with a fix by tomorrow, please post it here or make a PR.  I'll accept it.

Thanks

**Comment by Zeblote** [comment]
Yes a new clone. I don't have VS 2017, only the latest version of 2019 with the toolset and SDK installed.

One thing I noticed is that these projects try to use a platform called "Gaming.Desktop.x64" rather than "x64" like the other samples. Is that the issue? What's "Gaming.Desktop.x64"? I'm getting zero search results.

**Comment by DrGr4f1x** [comment]
I'm also on a fresh clone, no local changes.  I only have VS 2019 Professional installed (never had 2017 on this box).  VS 2019 is updated to latest, incl. toolset and SDK.  The only slightly unusual thing about my setup is that I also have the latest Windows Driver Kit installed, to build DXC locally.  Otherwise it's a pretty vanilla setup (off a clean Win 10 reinstall about 6 weeks ago).

**Comment by stanard** [comment]
It's possible mine builds locally because I have the GDK (Game Developer Kit) installed, which is only available to Xbox licensees.  That's what the "Gaming.Desktop.x64" refers to, but I didn't anticipate it would matter.  I wanted to keep the Xbox-friendly version of MiniEngine as similar to the Desktop-only version as possible.  I'll uninstall the GDK and try again.  Should I repro the problem, I'll then fix it and commit a patch.  Sorry for the hassle!

**Comment by Zeblote** [comment]
Randomly tried replacing those "Gaming.Desktop.x64" with "x64" and it results in it trying to build, but it doesn't get very far because _GAMING_DESKTOP is not defined. Manually defining that results in these errors:

![image](https://user-images.githubusercontent.com/6764788/109400240-db129880-7947-11eb-8761-d02c5f428699.png)

**Comment by stanard** [comment]
You should be able to fix those linker errors by adding some linker dependencies:  d3d12.lib, dxgi.lib, and runtimeobject.lib, I believe.  I had to add them to the D3D12RaytracingMiniEngineSample too, so you could double check there.

**Comment by stanard** [comment]
I pushed the fix for this, but I was having trouble uninstalling the GDK, so I have not been able to confirm that it truly builds without errors for others.  But since it's not targeting Gaming.Desktop.x64, it won't be relying on GDK configuration scripts, and I did have to manually define _GAMING_DESKTOP.  Please let me know if all is well now.  Thanks!

**Comment by DrGr4f1x** [comment]
I just pulled latest and I can build.  Thanks for the quick turnaround on
the fix!
