### ISSUE TITLE
D3D12Raytracing.sln fails to compile with MSB8020

### ISSUE THREAD

**Issue by henning-semler** [microsoft/DirectX-Graphics-Samples#698]
I've done a full reinstall of VS2019 Community Edition 16.9.0 just to be sure there is nothing wrong. 
I've verified that it has installed these components:
* MSVC v142 - VS 2019 C++ x64/x86 build tools (Latest)
* C++/CLI support for v142 build tools (Latest)

I get the following error when trying to build:

```
Rebuild started...
1>------ Rebuild All started: Project: Core, Configuration: Debug Gaming.Desktop.x64 ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): error MSB8020: The build tools for v142 (Platform Toolset = 'v142') cannot be found. To build using the v142 build tools, please install v142 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
1>Done building project "Core.vcxproj" -- FAILED.
2>------ Rebuild All started: Project: Model, Configuration: Debug Gaming.Desktop.x64 ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): error MSB8020: The build tools for v142 (Platform Toolset = 'v142') cannot be found. To build using the v142 build tools, please install v142 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
2>Done building project "Model.vcxproj" -- FAILED.
```

Any clues?
Henning

**Comment by stanard** [comment]
This did not repro for me.  Can you confirm that you have pulled the latest commit of the 'master' branch?  You might try modifying the ToolsVersion at the top of ModelViewer_VS16.vcxproj to "16.0".  There are some other adjustments I would make to try to fix this, but since I'm not seeing the error, I don't know what change would fix it for you.

And then another thing you can try is following the directions to "Retarget solution" to v142.  See what changes in the project files (and please report back what those changes were if it works.)

You might also try a Rebuild All to remove stale binaries.

**Comment by henning-semler** [comment]
Ah - I missed your last commits for the missing GDK - sorry about that. It's compiling fine now.
Thanks for helping out!

Henning
