### ISSUE TITLE
All Desktop samples have a major content shifting issue after resizing a window

### ISSUE THREAD

**Issue by joelriendeau** [microsoft/DirectX-Graphics-Samples#705]
This is not just a flickering issue during resize. The content gets shifted up by about the same distance as the size of the title bar, and also a bit to the left.

But the worst part is the content stays shifted even after resize is finished. The only way to fix the issue is to then move the Window a little bit, and the frame buffers gets re-centered correctly.

This is reproducible on every graphics sample I tried. I use an up-to-date Windows 10.

I have seen the same issue in multiple other windowed D3D12 applications. This feels like a system-wide regression in DWM or D3D12.

**Comment by jenatali** [comment]
Thanks, we're taking a look. Since this isn't really a problem with the samples, a more appropriate avenue probably would've been feedback hub or our DirectX Discord server.

**Comment by joelriendeau** [comment]
Ok thanks, didn't know where else to post. Noted.

**Comment by paulbartrum** [comment]
I had the same issue. I tracked it down to a display driver bug that was fixed in NVidia display driver version 461.92. From their release notes:

"Some desktop applications may flicker or stutter when resizing the window on some PC 
configurations [3252200]."

And indeed, updating to the latest version of the driver fixed the problem. So you can likely close this issue.

**Comment by jriendeau-cradle** [comment]
Yes a driver update also fixed the issue. Sorry, the debugging happened on Discord, I forgot to reply here.

**Comment by PixelRick** [comment]
And this issue reappeared apparently. Last nv drivers installed 556.12.
