### ISSUE TITLE
Collision handling of PSO hash value

### ISSUE THREAD

**Issue by pengliu916** [Microsoft/DirectX-Graphics-Samples#82]
Hi 

In MiniEngine, it seems you guys use hash map to avoid compiling duplicated PSOs (also use hash to avoid expensive duplicated pso bindings). But I can't find anywhere that how you guys handles collisions. So I guess in some case where we have a lot PSOs, we may possibly have incorrect rendering due to PSO hash value collision? (though the possibility is very low)

Am I miss something or the collision is handled somewhere else?

Thanks

Peng

**Comment by weltkante** [comment]
I'd guess because it's a sample and because it's not user-input-driven they skipped that to keep the code simpler. In the (very unlikely) event of a collision you'd just treat it as a bug in the shader source which is discovered and fixed like any other bug.

The program complexity and runtime performance gains are preferable to the cost of something that is not supposed to happen.

**Comment by stanard** [comment]
Hash collisions are to be expected, and they indicate a duplicate object.  We avoid duplication by checking an STL map for pre-existing hash values.  (Essentially a hash map.)  Unexpected collisions (where two completely different series of bytes yield the same hash value), on the other hand, should be so exceedingly rare as to probably never be noticed.  If unexpected collisions do arise, I'd suspect you have a different bug (such as in the hashing system itself.)
