### ISSUE TITLE
MiniEngine: In ModelViewer.cpp USE_VERTEX_BUFFER =1 crashes driver.

### ISSUE THREAD

**Issue by RogersDoug** [Microsoft/DirectX-Graphics-Samples#86]
If you use verterx buffers to render by changing USE_VERTEX_BUFFER to 1
in ModelViewer.cpp, line 39, you will get this error on an NVIDIA GTX 970 Ti.  Driver 361.43

D3D12: Removing Device.
D3D12 ERROR: ID3D12Device::RemoveDevice: Device removal has been triggered for the following reason (DXGI_ERROR_DEVICE_HUNG: The Device took an unreasonable amount of time to execute its commands, or the hardware crashed/hung. As a result, the TDR (Timeout Detection and Recovery) mechanism has been triggered. The current Device Context was executing commands when the hang occurred. The application may want to respawn and fallback to less aggressive use of the display hardware). [ EXECUTION ERROR #232: DEVICE_REMOVAL_PROCESS_AT_FAULT]
Exception thrown at 0x00007FF8D1211F08 in ModelViewer.exe: Microsoft C++ exception: _com_error at memory location 0x0000003E146FD030.
Exception thrown at 0x00007FF8D1211F08 in ModelViewer.exe: Microsoft C++ exception: _com_error at memory location 0x0000003E146FD1C0.
Exception thrown at 0x00007FF8D1211F08 in ModelViewer.exe: Microsoft C++ exception: _com_error at memory location 0x0000003E146FD030.
Exception thrown at 0x00007FF8D1211F08 in ModelViewer.exe: Microsoft C++ exception: _com_error at memory location 0x0000003E146FD1C0.

**Comment by bobbrow** [comment]
You also need to set USE_VERTEX_BUFFER to 1 in ModelViewerVS.hlsl and DepthViewerVS.hlsl.  I set all 3 instances to 1 and everything renders fine on that driver for me.  If I only set the one in the .cpp file then the device will be removed.

**Comment by RogersDoug** [comment]
I just saw that.  This is poor coding practice.  There should be a single include file that set this.

**Comment by RogersDoug** [comment]
There is a line in the shaders:
"#elif USE_ROOT_BUFFER_SRV"
but this is not defined in any shader code.  This also should be in a shared header file.

**Comment by Postal86** [comment]
Can i run on Geforce  GT  630  Card ?   Nvidia Web   says that  DX  12 api is supported,  when i  have downloaded  and  tried   to  run  some  kind of  Exception  is popping up on  my monitor , i could not  figure out reason is Driver  or GPU does  not  supported  but  i  think  first  one more  relevant, because  if  issue  is  GPU i think  different  error would be shown and more clear  error  would  pop up. What  u  think pals ?! :)

**Comment by stanard** [comment]
We left some optional code paths in MiniEngine for our benefit (like validating driver functionality), but we don't expect people to arbitrarily turn on these other code paths.  Perhaps this extra code is a distraction and we should remove it from the GitHub branch of MiniEngine.  I thought this particular code split was educational because it shows three different ways to stream vertices:  a vertex buffer, a buffer pointer, and a buffer descriptor.  But it's not well documented, as you noticed.  Control flow #defines should be in one place for easy changes.  I'll make the changes.  Thanks.
