### ISSUE TITLE
Cannot get vainfo to show any non-trivial profiles on Windows 10

### ISSUE THREAD

**Issue by anders-gaarde** [microsoft/DirectX-Graphics-Samples#885]
Hi all,

I have a question about using VA-API in Windows 10, cf. https://devblogs.microsoft.com/directx/video-acceleration-api-va-api-now-available-on-windows/ 

The linked page says that WIndows 10 should be supported, but I only see trivial profiles from vainfo on Windows 10. See for example attached output from the version of vainfo included with microsoft.direct3d.videoaccelerationcompatibilitypack v1.0.2 on a Dell Precision 7560 - I am fairly certain the hardware supports various decoding profiles, so what am I doing wrong?

On Windows 11 (on different machines), I see the expected profiles.

![image](https://github.com/user-attachments/assets/d5ddbc9b-7208-471a-9529-30d7cd4ee0b9)

**Comment by sivileri** [comment]
Hi @anders-gaarde , I think you're hitting this issue https://gitlab.freedesktop.org/mesa/mesa/-/issues/9824. It was fixed in https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/25272 but that wasn't included in the latest nuget yet. 

`vainfo` will not show the profiles since it's loading the Win 10 OS D3D12 library version, but could you please try on Win 10 with some other samples such as [DirectX-Samples/HelloVaEncode](https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12HelloWorld/src/HelloVAEncode) ? Those projects should be using the [Agility SDK](https://devblogs.microsoft.com/directx/gettingstarted-dx12agility/) 1.613+ D3D12 library version and should unblock you if you're attempting to develop an app with VAAPI that can use [Agility SDK](https://devblogs.microsoft.com/directx/gettingstarted-dx12agility/).

In the meantime, another alternative would be to build manually `vaon12_drv_video.dll` from [upstream mesa](https://gitlab.freedesktop.org/mesa/mesa) that contains the fix, by following [these instructions from mesa](https://docs.mesa3d.org/install.html) and configuring with `-Dgallium-drivers=swrast,d3d12 -Dgallium-va=true`

**Comment by anders-gaarde** [comment]
Hi Sil, thank you so much for the quick response!

The HelloVaDecode/Encode app did not work out of the box, but your answer led me on the right path: Adding the lines 

```
extern "C" { __declspec(dllexport) extern const UINT D3D12SDKVersion = 613; }
extern "C" { __declspec(dllexport) extern const char* D3D12SDKPath = u8".\\D3D12\\"; }
```

to the top of D3D12HelloVaDecode.cpp did indeed make it load the 1.613 version of the D3D12 dlls, which solved my issue.

Thanks again!

Anders
