### ISSUE TITLE
Need sample on Ring-Buffers

### ISSUE THREAD

**Issue by toomuchvoltage** [Microsoft/DirectX-Graphics-Samples#91]
I was wondering if we could have a small sample demonstrating this : https://msdn.microsoft.com/en-us/library/windows/desktop/dn899217%28v=vs.85%29.aspx#gpu_engines

I don't know if it's just me but I've found it very difficult to find examples on this. If I'm not mistaken, it's essentially having copy queues/command-lists with a ring buffer... though I'm not sure what type of buffer the ring buffer is (placed resource?tiled?multiple committed ones?). I'm basically a long time OpenGL guy returning to D3D12 after a very long D3D-hiatus... and I know in OpenGL things like this are done with variable-length-Buffered PixelBufferObjects (PBOs) for asynchronous texture uploads (useful for streaming images from a decoder or somesuch.)

Anyway, a sample or even some clear direction on how to achieve this would be highly appreciated.
I've also looked at : https://msdn.microsoft.com/en-us/library/windows/desktop/dn899125%28v=vs.85%29.aspx but didn't manage to gather much.

Again, thanks in advance for looking into this.

Yours truly,
Baktash.

**Comment by toomuchvoltage** [comment]
I just added a sample code (using my wrapper) for trying to do this with placed resources, a shared upload heap and UpdateSubresources(...): https://github.com/toomuchvoltage/GAL/blob/master/GALProject/test_src/ring_buffer.cpp
You could even perhaps provide me with feedback on whether or not that is an optimal solution and if not, what kind of changes would be necessary to achieve optimal performance.

Thanks,
Baktash.

**Comment by bobbrow** [comment]
It's a little hard for me to tell exactly what your synchronization looks like since you've wrapped everything up in some other classes, but based on the method names, it would appear that the waiting is being done on the wrong processor.

Rather than signal and wait on the copy queue (the code appears to be doing a wait on the CPU... I can't tell), you want to signal on the copy queue and then issue a wait on the 3D queue (waiting on the GPU).  This allows you to keep the CPU busy and get all of the work onto the GPU sooner instead of unnecessarily waiting on the CPU to submit the work after the GPU is idle.  For example:

```
...
copyQueue->ExecuteCommandLists();
copyQueue->Signal(copyFence, 100);
renderQueue->Wait(copyFence, 100);  // GPU-wait for the copy to complete.
renderQueue->ExecuteCommandLists();
...
```

As far as the ring buffer goes, I would expect this to vary depending on the application.  The D3D12PipelineStateCache sample uses a committed resource as the ring buffer for the constant buffers since the API only requires GPU virtual addresses and not ID3D12Resource pointers.  See [DynamicConstantBuffer.cpp](https://github.com/Microsoft/DirectX-Graphics-Samples/blob/master/Samples/D3D12PipelineStateCache/src/DynamicConstantBuffer.cpp).  I have a backlog item to write a sample for placed resources so showcase how applications can take advantage of 4KB texture alignments to save memory (instead of the 64K alignments enforced by committed and reserved resources).

**Comment by toomuchvoltage** [comment]
Thank you Bob. I corrected the mistake.
Really appreciate the feedback!
I'll be on alert for the arrival of the placed resources example! ;)

Yours truly,
Baktash.
